### ISSUE TITLE
Documentation Contents CeedEvalMode are duplicated

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1000]
https://libceed.org/en/latest/api/CeedBasis/#c.CeedEvalMode

The values of the enumerator are duplicated 3 times:
![image](https://user-images.githubusercontent.com/20801821/174685015-95bd33b7-aec2-4aab-9aec-533b6ca5a510.png)

Haven't investigated as to why, though I have a feeling it's probably on the Doxygen side?

**Comment by jeremylt** [comment]
Its showing in the Doxygen output:
![image](https://user-images.githubusercontent.com/25011573/174917319-19ff7aa3-5aa2-4077-a52a-cfd3027d68e4.png)
