### ISSUE TITLE
Projection Basis Gradient

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1017]
> We have $B_p = B_f^\dagger B_c$ and I think $D_p = B_F^\dagger D_c$ is the gradient, in the sense that $B_f D_p \approx D_c$ (exactly when c is a subset of the space f).

**Comment by jrwrigh** [comment]
(stemming from this discussion: https://github.com/CEED/libCEED/pull/1009#discussion_r915291376 )
