### ISSUE TITLE
Proposed API improvements

### ISSUE THREAD

**Issue by Steven-Roberts** [CEED/libCEED#103]
After going through the new active/passive changes, it seems that some parts of the code expect an `emode` to be a single `CeedEvalMode` while others still accept multiple values anded together.  When a user calls `CeedQFunctionAddInput` or `CeedQFunctionAddOuput` it seems reasonable to only expect a single `emode` to be provided.  If so, I think the basis api can be cleaned up a bit.

Proposed changes:
Replace
https://github.com/CEED/libCEED/blob/0771ec9989bc3dfb577315a80cc0b18e86cb2dd3/include/ceed-impl.h#L86-L87
with function pointers for interp, grad, weight, div, curl, etc.  Then, have `CeedBasisApply` be the single function to perform a switch on `emode` to call the appropriate function pointer.  Currently there are a ton of switch statements scattered across the basis and operator files which makes the code fragile.  If a new feature like a laplacian were to be added, an unnecessarily large number of files would need to be updated.  I think it should reduce code duplication and allow for simplifications in backend operators

**Comment by jedbrown** [comment]
Good observation about moving away from allowing combined `CeedEvalMode`. Note the implementation in `CeedBasisApply_Opt` (#82) where the INTERP is computed as an intermediate result of GRAD (we should put it in the useful place when needed).

There is a bit of code duplication already in `CeedBasisApply_Ref` and I'm not sure that splitting it into different functions is more maintainable than merging it.

When you say "Laplacian", do you mean the operator or just computing second derivatives (e.g., for a stabilization operator or H^2/fourth order problem)?

**Comment by Steven-Roberts** [comment]
@jedbrown By laplacian I mean div(grad(u)).  Just a random example of a new eval mode.  The problem I see is that adding a new eval mode would require many changes in the operator files when it probably shouldn't.  Splitting up these eval modes will not really make something like `CeedBasisApply_Ref` any more maintainable, but it can significantly help `CeedOperatorApply_Ref`.  Switch statements like

https://github.com/CEED/libCEED/blob/0771ec9989bc3dfb577315a80cc0b18e86cb2dd3/backends/ref/ceed-ref-operator.c#L261-L282

where code is duplicated in cases could be replaced with a single call to `CeedBasisApply` perhaps with special cases for `CEED_EVAL_NONE` or `CEED_EVAL_WEIGHT`.

@jeremylt Good point about the input/output sizes.  A new function such as `int CeedBasisOutputLength(CeedBasis basis, CeedEvalMode emode, CeedInt *outputLen)` could be used as opposed to duplicating the switch statement and its calculations in every backend.  Then the operators would no longer need any switch statements.

**Comment by Steven-Roberts** [comment]
I think the best solution to this situation would be to stop letting backends provide implementations for an operator.  A single, generic implementation could be written in `CeedOperatorApply`.  Most backends are already using backend-independent functions like `CeedVectorGetArrayRead`, `CeedElemRestrictionApply`, etc.  I realize this is a more significant change, but I think it could be quite beneficial long-term.

**Comment by jedbrown** [comment]
That's a fair point, though optimized backends will be doing various kinds of batching and possibly fusion that may not be appropriate for a public interface. We should refactor `ref` to make it cleaner, but don't expect that every backend will have the luxury of separating concerns so well.

Also note that some backends will want to move through elements in batches (e.g., 8 at a time), thus won't `CeedElemRestrictionApply` because they never store a complete E-vector.

**Comment by Steven-Roberts** [comment]
Perhaps a compromise could be a default `CeedOperatorApply` which can be overridden if needed.  The ref, magma, and now cuda operators have almost identical code aside from variable names.  This suggests a default would simplify things a lot.

**Comment by jedbrown** [comment]
I would be happy to merge that.

```
if (op->Apply) {
  // call it
} else {
  // default implementation
}
```

**Comment by jeremylt** [comment]
If we fix the OCCA backend memory copy issues if we could include it in the common code too. This would require pulling Operator setup up to common code or leaving in the backend but making it callable from the library level. Those functions use the private backend data struct and I don't know that we want to be playing with that struct from the library level rather than the backend level.

I'm not opposed to the idea, I just not convinced it's the best best way to do this. especially given that this should be a temporary problem as backends other than `ref` will eventually specialize their `OperatorApply`to best provide speed.

It might make more sense to implement this sort of through a call to a held reference backend, like with `tmpl`. That would be a less disruptive change with the same effect.

**Comment by Steven-Roberts** [comment]
Ideally optimizations would not need to be made in `OperatorApply`: they would just be made in `QFunctionApply`, `BasisApply`, and `ElemRestrictionApply`.  It would just act as a lightweight function orchestrating the inputs and outputs to all the restriction, basis, and qfunction.  Currently, this is not possible due to the looping over elements in an operator (and maybe other reasons).  Thus your optimizations like batching are caught up in the operator.  The operator for-loop needs to be pushed into `BasisApply` and `ElemRestrictionApply`, and these function should accept Vectors as arguments (like `ElemRestrictionApply`).  These changes need to be made anyway for the cuda and occa backends.  Otherwise, the basically run serially and do a ton of extra memcpys.  If these changes are made I think most if not all backends could have optimizations and use a default operator.

**Comment by jeremylt** [comment]
I am not sure we can fully push the element looping into the `BasisApply` function as CPUs would still want to handle batches at a time through the entire process (input basis action, qfunction action, output basis action) whereas it's better to act on all elements at a time for GPUs, as I understand it.

I suppose we could combine them by having a loop over batches where the batchsize is all elements for GPU and just 8 or so elements for CPUs.

Modifying `BasisApply` to accept multiple elements I agree is needed and something that I am working on today for the Opt backend. OCCA had that functionality but it looks like they temporarily moved away from it to get active/passive working. 

Again, I'm not disagreeing with the idea of collecting the common code, I'm just not convinced that it belongs at the library level. I don't like the idea of modifying the backend Operator data structs from the library level, so we would need to figure out how to handle that.

It feels more natural to me for us to set up a default implementation in Ref and have other backends call through to that implementation, like is done with the `tmpl` backend.

**Comment by Steven-Roberts** [comment]
Good points.  Adding a batch size parameter to `BasisApply` seems like a nice and flexible solution.  I also agree that writing a default implementation in Ref and reusing it using the strategy in `tmpl` seems better.  That could also allow the cuda operator to use occa one while the opt uses the ref operator, for example.  Seems like a nice balance of code reuse and flexibility.

**Comment by jeremylt** [comment]
Thanks for getting this discussion started - I just had to manually adjust the same code in 3 backends for #104 and it was annoying. This common code collection is past due.

**Comment by Steven-Roberts** [comment]
With PR #110 merged, one piece of this discussion has been solved.  For consistency, it seems natural to have `QFunctionApply` to take `nelem` as an argument too.  It might be a bit messy since the stride for each input and output must be passed in as well.  Perhaps it would be reasonable to keep that one as is.  Backends that parallelize qfunction evaluation can take care of that in the operator.

Also, `BasisApply` and `QFunctionApply` could benefit greatly from taking `Vector`s as arguments.  Can we start a PR for this if everyone is in agreement?

**Comment by jeremylt** [comment]
I'm not sure I see the different between passing a memory location and a size (blksize) vs the entire element. Can you expand on what you are thinking?

As far as `QFunctionApply` that seems to make sense, though maybe we can get by that by passing `Q*blksize` as the number of quadrature points?

**Comment by Steven-Roberts** [comment]
What do you mean by blksize?

Let me clarify.  It would be nice for `QFunctionApply` to work over any number of elements to allow for parallelization.  This means instead of taking one set of inputs and outputs, it has `nelem`.  So the qfunction becomes responsible for indexing all the `u` and `v` vectors.  Inputs and outputs may have different lengths (e.g. grad is dim times bigger than interp), so qfunction needs stride information for each.  Basically, the indexing logic in the operator would need to be pushed in the qfunction.

For GPU backends, `Vector` args can save 2 copies to and from device.  It is also consistent with the element restriction interface.

**Comment by jeremylt** [comment]
So we have a blocksize of 8 elements. I am trying to set things up so that I can do a single call to `QFunctionApply` with `8*Q` quadrature points for each batch/block of elements. I think that the basis actions on interlaced elements arrange all of the quadrature data relative to each other properly so I can work across all interlaced elements in the batch.

I think memory movement is a topic of discussion this week at the annual meeting. My understanding is that the GPU backends would like to not copy back to the host until the end of `OperatorApply`, right? So wouldn't `BasisApply` and `QFunctionApply` be best served only working on the device? I only loosely understand GPU optimization, so I'm trying to clarify my understanding here.

**Comment by jedbrown** [comment]
> It would be nice for QFunctionApply to work over any number of elements

It can because it doesn't care which element a given quadrature point corresponds to. It's important for QFunction implementations to make indexing as simple as possible because users write that code and anything extraneous or error-prone will be a huge turn-off to this type of interface.

**Comment by jedbrown** [comment]
GPU backends should never copy back to the host unless the user requests it (e.g., `CeedVectorGetArray` with `CEED_MEM_HOST`). Sophisticated users may pack their send and receive buffers on the device and use GPUDirect.

**Comment by Steven-Roberts** [comment]
@jeremylt What I am suggesting is completely separated from the blocking.  Think of a non-SIMD openmp backend for example.  Right now `QFunctionApply` only works on one element at a time.  @jedbrown yes this can be any single element in the mesh given a proper implementation.  I'm saying it should be able to accept all elements at once to allow parallel evaluation.

For the memory management, @jedbrown is right.  That is what I do for the CUDA backend.

**Comment by jeremylt** [comment]
I have code in my branch where `QFunctionApply` is working on 8 elements at a time. I really don't think it cares how many elements we hand it...

**Comment by jedbrown** [comment]
@Steven-Roberts `QFunctionApply` really works on any number of elements. If you build contiguous Q-vectors, you can evaluate over all quadrature points of all elements in the mesh (mixed topology/order or not) in one call to `QFunctionApply`.

**Comment by Steven-Roberts** [comment]
Sorry, I'm a bit confused.  @jedbrown In you example, would the `Q` passed to `CeedQFunctionApply` be `nelem` times the number of quadrature points per elem.  And `vlength` would be `nelem`?

**Comment by jedbrown** [comment]
`vlength` in the constructor is a constraint that the caller must honor. (`Q` must be divisible by `vlength`, so the caller is responsible for padding or batching to ensure that). The intent is to allow implementations to use vectorization without needing to worry about fringes. QFunctions without explicit vectorization can just use `vlength = 1` and the compiler will manage fringes (in many cases it will perform fine). If calling `QFunctionApply` on a batch of (possibly heterogeneous) elements, you would use

    Q = \sum_{e \in elements} numquadpoints(e)

**Comment by jedbrown** [comment]
Why would `f_build_mass` care how many elements it is run on?

For batching, see https://github.com/CEED/libCEED/tree/opt-vectorize (incomplete)

**Comment by jeremylt** [comment]
I think we have incorporated many of these for now and have decided to wait on others for now. Can we close/archive this for now? Or reopen a smaller issue if there are still lingering parts?

**Comment by jeremylt** [comment]
With PR #174 all of these concerns will have been adjudicated.
