### ISSUE TITLE
CI: better parallelism in integration tests

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#1062]
It's relatively harmless for the `t*` tests to run all backends, but the integration tests (especially fluids) take a long time because there are many `//TESTARGS` lines and we currently run through them sequentially. It would be nice to make it possible to run each line separately and/or run the sequence over one backend per parallel task. This would greatly reduce our current testing time. I suppose one way to do this would be to move the `//TESTARGS` stuff into separate files (could become yaml files).

**Comment by jeremylt** [comment]
I think we have this improved parallelism now. There's been some chatter about switching to a different test harness, but I think that's a separate issue?
