### ISSUE TITLE
Multiple Active Basis Diagonal Assembly

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1087]
Currently we don't support assembly for a CeedOperator with different bases acting upon the active vector, but we now have a use case for that.

https://gitlab.com/micromorph/ratel/-/merge_requests/233

We can reformulate this specific CeedOperator to use the same bases, though at the expense of efficiency.

It would be good to add the capability to handle different bases acting on the same active vector. We have some other use cases for this in the works as well.

The CPU side should be tedious but straightforward. Once we get the CPU version merged, we can handle the GPU versions.

**Comment by jeremylt** [comment]
The QFunction assembly should be fine.

I think this has 4 parts:

1) CPU diagonal assembly

2) CPU full assembly

3) GPU diagonal assembly

4) GPU diagonal assembly


---

CPU diagonal assembly is the most straightforward and gives us a sense of what we need to do for the rest, so we should start there.

The skeleton of the current diagonal assembly code is

```C
static inline int CeedSingleOperatorAssembleAddDiagonal_Core(CeedOperator op, CeedRequest *request, const bool is_pointblock, CeedVector assembled) {

  // Assemble QFunction
  // -- Should not need changes

  // Get assembly data
  // -- Will need array of active bases here

  // Assemble point block diagonal restriction, if needed
  // -- Will need array of active restrs here, may need multiple point block restrs

  // Create diagonal vector
  // -- Should only need minor tweaks to handle array

  // Assemble element operator diagonals
  // -- Should only need minor tweaks to handle array

  // Basis matrices
  // -- Will need array of interp and grad matrices in/out (eventually will want div too)
  // Compute the diagonal of B^T D B
  // Each element
  for (CeedInt e = 0; e < num_elem; e++) {
     // -- num_elem will be the same across all bases
    // Each basis eval mode pair
    for (CeedInt e_out = 0; e_out < num_eval_mode_out; e_out++) {
      for (CeedInt e_in = 0; e_in < num_eval_mode_in; e_in++) {
        // -- Getting basis matrices for emode should only need minor tweaks
        // Each component
        for (CeedInt c_out = 0; c_out < num_comp; c_out++) {
           // -- num_comp should depend upon the specific basis
          // Each qpoint/node pair
          for (CeedInt q = 0; q < num_qpts; q++) {
            // -- q must always be the same across all bases
            if (is_pointblock) {
              // Point Block Diagonal
              for (CeedInt c_in = 0; c_in < num_comp; c_in++) {
                for (CeedInt n = 0; n < num_nodes; n++) {
                  // -- num_comp, num_nodes depend upon the specific basis
                }
              }
            } else {
              // Diagonal Only
              for (CeedInt n = 0; n < num_nodes; n++) {
                // -- We'll need to make sure the num_nodes matches the nodes for the basis
                // -- Also want separate vectors for each different active basis/restr
              }
            }
          }
        }
      }
    }
  }

  // Assemble local operator diagonal
  // -- Will need to loop over all different output restrs

  // Cleanup
  // -- Only need changes to account for multiple bases/restr

  return CEED_ERROR_SUCCESS;
}
```

So, changes that stand out to me

1) Add functions to get array of active bases/restrs in and out

2) Adjust code to accommodate arrays of bases/restrs + interp/grad matrices

3) Separate e-vector to fill for each output

4) num_comp, num_nodes differ for each basis

We'd need to chase similar changes back into the blocked/opt CPU backends. The challenge there is adding the same changes while also respecting the loop over the blocking strategy.

**Comment by jeremylt** [comment]
Do those comments make sense? Am I missing anything obvious that will trip us up?

**Comment by rezgarshakeri** [comment]
I don't understand this comment `// Compute the diagonal of B^T D B` in the above skeleton, Do you want to do matrix multiplication there?
For a mixed problem, the operator create this form
$$\left\lbrack \matrix{A & B \cr C & D} \right\rbrack$$
 (for a symmetric case we hace $B = C^T$), We want to create a preconditioner of the form 
 $$\left\lbrack \matrix{\operatorname{diag}(A) & 0 \cr 0 & -S} \right\rbrack$$
 where $S = D - C \operatorname{diag}(A)^{-1}B$. (for the symmetric case $S = D - B^T \operatorname{diag}(A)^{-1}B$)
 My understanding was to assemble each block and then do the matrix multiplication out of the backends or I am wrong?

**Comment by jeremylt** [comment]
This function outlined above is just for assembling the diagonal of a single libCEED operator, so

 $$\left\lbrack \matrix{\operatorname{diag}(A) & 0 \cr 0 & \operatorname{diag}(D)} \right\rbrack$$

assuming they both feed into the same QF

---

In the notes in the comments above, B is for the basis and D the QFunction, from the diagram [here](https://libceed.org/en/latest/libCEEDapi/#finite-element-operator-decomposition)
