### ISSUE TITLE
examples/fluids: Use generic MatShell operations for IJacobian

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1142]
As mentioned in this thread https://github.com/CEED/libCEED/pull/1135#discussion_r1072988454, the new MatShell operations are more-or-less equivalent to what is being done for the IJacobian. So replace `MatMult_NS_IJacobian` with `MatMult_Ceed` and `MatGetDiagonal_NS_IJacobian` with `MatGetDiag_Ceed`. 

Changing them into the new functions reduces redundant code.

**Comment by jeremylt** [comment]
Ratel did something similar, for comparison: https://gitlab.com/micromorph/ratel/-/blob/main/src/internal/ratel-petsc-ops.c

**Comment by jeremylt** [comment]
Did the linked PR end up fixing this issue, or is there more to do yet?

**Comment by jrwrigh** [comment]
It hasn't been done yet, just needs to be done at some point. Not high priority at the moment, though it's a quick fix anyways.
