### ISSUE TITLE
Add `CeedOperatorContextGetDouble` and friends for label data access

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1144]
A few questions for `CeedOperatorContextGetDouble` would be:
1) Is getting data access to the label expensive? 
   - ie. should we add a member to `CeedContextFieldLabel` that keeps track of the value to avoid trying to get access to the context (thinking GPU to CPU communication might be at play here)
2) For sublabels, do we trust that all the contexts will be the same value and, if not, what value do we return?

**Comment by jeremylt** [comment]
We should have one source of truth - the QFunction context itself. I rk we should let the context continue to figure out host vs gpu. 

For a label on a composite operator, I'd just document that it gets the first value and warn in the documentation that the function doesn't guarantee all suboperator values are the same. The usual context would be that they are the same, so I don't think we need to focus on this edge cane unless it becomes a problem is the future.

**Comment by jedbrown** [comment]
Is it a problem that IFunction composite operators include both interior and boundary contexts, the latter of which might be different (for inflow, outflow, and walls)? Should we walk all the sub-operators?

**Comment by jeremylt** [comment]
Could always group like suboperators in their own composite operators and then those composite operators into the final composite operator - though that may require minor fixes it the code

**Comment by jrwrigh** [comment]
If the data in those unique contexts are all under the same label, shouldn't they be the same? Or at least treated the same?

**Comment by jeremylt** [comment]
That is a good point

**Comment by jeremylt** [comment]
See #1148, I have proposed function signatures.
