### ISSUE TITLE
Sycl Backend PR follow ups

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1230]
Minor todos following up the Sycl backend PR https://github.com/CEED/libCEED/pull/1229

Todos (possibly split into separate issues and/or PRs):
- [x] Create generic `CeedSetStream` interface (see https://github.com/CEED/libCEED/pull/1229#discussion_r1229920227)
- [x] Consolidate `CeedGetResourceRoot` into a single interface (see https://github.com/CEED/libCEED/pull/1229#discussion_r1228850985)
- [x] Re-enable CPU Sycl backends (see https://github.com/CEED/libCEED/pull/1229#discussion_r1230276875)
- [x] Allow for compiler flexibility when building (see https://github.com/CEED/libCEED/pull/1229#discussion_r1231319514)

**Comment by jeremylt** [comment]
- [ ] Scrub GPU backends for naming inconsistencies
