### ISSUE TITLE
Doxygen Image

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#125]
The image in the API documentation page is not showing up on Doxygen. It should be a easy fix.

**Comment by jeremylt** [comment]
![screenshot from 2018-08-15 13-32-14](https://user-images.githubusercontent.com/25011573/44168826-bad3a480-a08f-11e8-9da7-7a4a8b955aa4.png)
I'm still seeing the issue

**Comment by jedbrown** [comment]
Reload that page.

**Comment by jeremylt** [comment]
Ok, now it's good. I had reloaded but I guess Doxygen hadn't caught up yet.
