### ISSUE TITLE
`CeedSingleOperatorAssemble` with rectangular operators

### ISSUE THREAD

**Issue by sebastiangrimberg** [CEED/libCEED#1277]
Right now, the assertion at https://github.com/CEED/libCEED/blob/main/interface/ceed-preconditioning.c#L590 fails when trying to fully assembly a rectangular operator with different input and output bases. Looking at the code, I think it should still work (so long as there is only one single active input basis and one single active output basis). However, I'm not very familiar with this multiple-active-bases concept so wanted to ask first. Does this look like an easy thing to fix?

**Comment by jeremylt** [comment]
Easy? Probably not. Its conceptually straightforward but it will probably be tricky debugging. I'd start by creating a `t5*` test that expresses the bug.
