### ISSUE TITLE
Choice of tiling and striding in OKL for kRestrict1

### ISSUE THREAD

**Issue by tcew** [CEED/libCEED#128]
This code partitions the element list with one element per thread. This means that the access to vv will have strided access with stride: ncomp*elemsize. Ideally, the thread-block of TILE_SIZE threads should access the data in contiguous chunks of size TILE_SIZE. The code as is will potentially suffer significant cache misses. Does this code achieve a significant fraction of peak dram_read/write_throughput according to nvprof ?

```
@kernel void kRestrict1(const int ncomp,
                        const int *indices,
                        const double* uu,
                        double* vv) {
  for (int e = 0; e < nelem; e++; @tile(TILE_SIZE,@outer,@inner)){
    for (int d = 0; d < ncomp; d++){
      for (int i=0; i<elemsize; i++) {
        vv[i+elemsize*(d+ncomp*e)] =
          uu[indices[i+elemsize*e]+ndof*d];
      }
    }
  }
}
```

**Comment by jedbrown** [comment]
This code runs very slowly on CPU and GPU. (I think @camierjs intends to work on its optimization in the coming weeks.) It should likely use the newish interface `CeedElemRestrictionCreateBlocked` at setup time so that access can be coalesced at `TILE_SIZE`.

**Comment by tcew** [comment]
Good to know.

Some other options:

```
@kernel void kRestrict1(const int ncomp,
                        const int *indices,
                        const double* uu,
                        double* vv) {
  for (int e = 0; e < nelem; e++; @outer(0)){ // thread-block loop
    for (int i=0; i<elemsize; i++; @inner(0)) {  // thread loop
      int ind = indices[i+elemsize*e]; // avoid multiple fetches from L1

       for (int d = 0; d < ncomp; d++){  // serial work for thread
         // this coalesces (modulo alignment) in i
          vv[i+elemsize*(d+ncomp*e)] =  uu[ind+ndof*d];
      }

    }
  }
}
```
There are a huge number of additional optimizations, but the above does not particularly cloud intent.

**Comment by camierjs** [comment]
All the OKL kernels are for now copy&paste from the reference implementation, we were focusing on getting the infrastructure working.

The active/passive fields API delayed the optimization phase of this branch, the CUDA one should be better.

I'll come back to these kernels with the new API in a few weeks; but if you have performing kernels, that would be great to use them instead of course.
