### ISSUE TITLE
Python Updates

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1283]
Two issues have come up in Ratel as points to discuss/fix here

- [x] Update the libCEED `junit.py` to reflect updates in Ratel's

- [ ] Discuss if we want to change Python linter [Black, ruff]

**Comment by zatkins-dev** [comment]
I think that it would be good to separate out the parts of `junit.py` which should be exactly the same between Ratel and libCEED to simplify maintaining parity in the future

**Comment by jeremylt** [comment]
True. A lot of it should carry over, except for the specific skip rules and paths to the source files
