### ISSUE TITLE
Testing fails due to walrus operator (`:=`)

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1331]
Looks like there's a walrus operator `:=` in the `junit_common.py` file, which makes it fail for Python 3.6 (it was introduced in 3.8). 

We could probably add a test of the python version to make sure it's capable of handling that. Or just not use the walrus operator.

Thoughts? @zatkins-dev @jeremylt

**Comment by zatkins-dev** [comment]
Ah, do you need to be using Python 3.6? I think that we should remove usage of the walrus operator, although I'm not sure why we would need to support Python <3.8. We should definitely have a target minimum python version, if we don't already.

**Comment by zatkins-dev** [comment]
To clarify, 3.6 is well-past EOL support: https://devguide.python.org/versions/

**Comment by jrwrigh** [comment]
HPC machines/admins often don't care about EOL, specially for system-installed packages. Other versions of Python _usually_ available, but not always easy to get at.

**Comment by jeremylt** [comment]
Using packages past the EOL is a failure on the part of *somebody*.

That said, it shouldn't be hard to remove the walrus. It is just a tiny bit of convenience syntax.
