### ISSUE TITLE
How does the CUDA Jit function?

### ISSUE THREAD

**Issue by knepley** [CEED/libCEED#1356]
I cannot find any documentation on its operation, or how to make it show me exactly what it is doing. I have a very simple PETSc project, which I am uploading. Wait, Github dos not support attaching C files or makefiles. Ridiculous. Anyway, here is the tarball.

[ex11.tgz](https://github.com/CEED/libCEED/files/12785500/ex11.tgz)

The problem is that when we select a CUDA backend

```
make run_sw EXTRA_OPTIONS="-dm_ceed /gpu/cuda/ref -cdm_dm_ceed /gpu/cuda/ref -dm_vec_type cuda -cdm_vec_type cuda"
```

we get an error from the CUDA compiler

```
/home/arcowie/petsc/arch-linux-rdycore-debug/externalpackages/git.libceed/backends/cuda/ceed-cuda-compile.cpp:93 in CeedCompile_Cuda(): NVRTC_ERROR_COMPILATION
default_program(371): error: identifier "PetscInt" is undefined
    PetscInt    dof;
    ^
```

which clearly happens because the compiler cannot see the includes. How do I tell it where the includes are?

**Comment by jeremylt** [comment]
The QFunction source file needs to include a definition of what a `PetscInt` actually means. I'm not sure what the best way to get those definitions into the QFunction source is.

**Comment by knepley** [comment]
So the current model is that no one ever use any headers for the QFunctions?

**Comment by jeremylt** [comment]
Nope. The current model is that you use local headers for the QFunctions.

**Comment by jedbrown** [comment]
Usually your qfunctions go in a header so that file can be compiled without including the source. The header containing your qfunctions can include other headers, but they need to be safe for processing by NVRTC/hipRTC

We don't want NVRTC/hipRTC to see extraneous host code so constructs in your host code can't break RTC, but it can be harmless.

**Comment by knepley** [comment]
@jedbrown So are you saying that if my kernel was in a header, it would compile?

I still would like documentation on exactly waht is happening. How does it decide what source is fed to the comoiler. How does it feed it? What flags are used? Can I change those flags?

**Comment by jrwrigh** [comment]
Yes, assuming the header file is readable at runtime and in the same file-system location.

To my understanding (not complete):
> How does it decide what source is fed to the comoiler. 

When you setup the QFunction (for example, via [`QFunctionCreateInterior`](https://libceed.org/en/latest/api/CeedQFunction/#c.CeedQFunctionCreateInterior)), a compile time `const` string is set to the absolute file path to the desired header file and the name of the function within that header file. See the `source` argument documentation for `QFunctionCreateInterior`.

Regarding the other questions, I'm not sure. I don't believe flags are exposed to the user to set, but I could be wrong.

**Comment by jeremylt** [comment]
> When you setup the QFunction (for example, via [`QFunctionCreateInterior`](https://libceed.org/en/latest/api/CeedQFunction/#c.CeedQFunctionCreateInterior)), a compile time `const` string is set to the absolute file path to the desired header file and the name of the function within that header file. See the `source` argument documentation for `QFunctionCreateInterior`.

Yeah. The GPU backends get the absolute path to the QFunction. You can include any other headers that can be reached via a relative path. You have to make sure that anything you include is mutually supported by C99 and CUDA/HIP.

I'm not aware of any way for you to manipulate the JiT from the outside. For this sort of situation, it would be really handy if PETSc had a `petsc-types.h`

**Comment by nbeams** [comment]
Yes, we currently do not expose JIT compilation flags to the user; you have to change them by modifying/adding to the `opts` array in `CeedCompile_Cuda`. 

The routine `CeedLoadSourceToInitializedBuffer` in `interface/ceed-jit-tools.c` searches the indicated source file for includes and tries to include those header files in the final code string that will be sent to the JIT compiler.

**Comment by jeremylt** [comment]
And yes, i can write better documentation. But not today. Probably not this week. My plate is pretty full.

**Comment by knepley** [comment]
I have moved everything to the header, but I am still getting a strange error
```
/home/arcowie/petsc/arch-linux-rdycore-debug/externalpackages/git.libceed/backends/cuda/ceed-cuda-compile.cpp:93 in CeedCompile_Cuda(): NVRTC_ERROR_COMPILATION
default_program(488): error: identifier "PetscFree" is undefined
    if (PetscFree(data)) return CeedError(NULL, CEED_ERROR_ACCESS, "PetscFree failed");
        ^
[ex11.tgz](https://github.com/CEED/libCEED/files/12787446/ex11.tgz)
```
I have attached the files to build. Should be easy for you to check.

**Comment by jeremylt** [comment]
Where is PetscFree defined?

**Comment by jeremylt** [comment]
Ah, I see. You are including a bunch of code that CUDA cannot compile in the same file and the QFunction source. The CUDA backend attempts to read the contents of the file you passed as the source and compile it with CUDA, but if that file contains things CUDA cannot compile, then JiT will fail.

This is why all of the QFunction source in the libCEED repos are in stand alone header files (or a series of related independent files with local includes)

**Comment by jeremylt** [comment]
Initial docs improvement in #1357, more to come (hopefully) when I have time (hahaha, such a funny joke there!)
