### ISSUE TITLE
ICC/IFort Action Failing

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1394]
Intel changed something again and the ICC/IFort job is failing. Not sure of the root cause yet.

**Comment by sebastiangrimberg** [comment]
The oneAPI install repos were just updated to 2024.0 I noticed. Maybe time to move to `icx`/`ifx`? If there aren’t any objections I’ll make a PR, let me know.

**Comment by sebastiangrimberg** [comment]
EDIT: Resolved in https://github.com/CEED/libCEED/pull/1391
