### ISSUE TITLE
Integer-valued quadrature data

### ISSUE THREAD

**Issue by sebastiangrimberg** [CEED/libCEED#1395]
As far as I can tell the answer is no, but I just wanted to check: Is there any capacity for integer-valued quadrature data? In particular, let's say we have a coefficient which takes on two different values in the computational domain and each element is tagged with a particular attribute which tells us which of the two coefficient values get used in that element. One approach here is to construct a `CeedOperator` for each part of the domain and then a `CompositeCeedOperator` for the whole thing, which I presume works OK but maybe sacrifices some performance due to needing to launch multiple kernels of smaller size. The alternative would be to have a single `CeedOperator` where one input to the QFunction is the attribute (`qdata_size = 1`) of the element and the particular coefficient values could be just stored in the QFunction context.

For now, I could make the second approach work by just storing the element attributes in a `CeedVector` as floating point values. I would be curious if anyone has addressed similar problems with different solutions or has any feedback on whether this is a good idea or not. Thanks!

**Comment by jeremylt** [comment]
The current "intended" path is to use composite operators. It works fine if there are only 2 possible values. For something like hundreds of values I think our current plan would be to put ints into a scalar `CeedVector`.

**Comment by jedbrown** [comment]
In order to avoid warp divergence, we want everything in a thread block to have homogeneous properties. I could imagine creating fused kernels for composite operators that carefully pad the iteration space to ensure this alignment, but I'm not aware of performance benefit for doing that. I realize that putting integer flags into floating point values isn't very satisfying, but it is exact (for a big range of integers) and avoids internal complexity that I'm not convinced pays off.

**Comment by sebastiangrimberg** [comment]
Ok just a related question here (let me know and I'll create a new issue if that's preferred). What's the recommended strategy, if there is one, for QFunctionContextData with some heap allocated memory? It seems like in all the examples I can find this struct is POD so it can be trivially copied/destroyed, with compile time array sizes. I'm thinking of cases where one or more members of the struct has a data size which isn't known at compile time.

Can flexible array members recommended/allowed in this case? Is there another better way, perhaps just with a pointer to data? Alternatively I thought about making one of the struct members a pointer to data and another a `CeedVector` owning said data, in which case the `CeedVector` gets destroyed using a function set by `CeedQFunctionContextSetDataDestroy`.

Anyway, sorry if this an annoying question but I'm curious if there are recommended approaches for this problem.

**Comment by jeremylt** [comment]
Unfortunately, CUDA seems to hate flexible array members.

**Comment by sebastiangrimberg** [comment]
Ah, of course. This might work though right:

```
struct VectorContext
{
  CeedVector v;
  const CeedScalar *v_data;
};
```

When creating the struct, we call `CeedVectorCreate`, and populate the vector data as we need. Then we call `CeedVectorGetArrayRead` with the correct (device) memory type to initialize `v_data`. Then from the QFunction we can use `v_data` as needed.

Lastly, when we set a destruction function for the `QFunctionContextData` which calls `CeedVectorRestoreArrayRead` followed by `CeedVectorDestroy`.

Am I totally off here or would this work?

**Comment by jeremylt** [comment]
That won't work on the GPU, but the CPU will use it fine

**Comment by jeremylt** [comment]
Or are you saying that you'd get the vector contents outside of the QFunction?

**Comment by sebastiangrimberg** [comment]
I'm saying we'd create the vector and initialize its contents, then get a device pointer to the data (GPU memory) before passing the struct to `CeedQFunctionContextSetData` with `CEED_MEM_HOST` and `CEED_COPY_VALUES` (the struct is on the host, but the pointer points to device memory). Then from inside the QFunction we never touch the `CeedVector`, only the associated (device) data in `v_data`. And finally when destroying the context the data is properly destroyed by the `CeedVector` destructor.

Sorry if I wasn't clear (or am still being confusing). I don't see why it would work on CPU but not GPU unless there's something I'm missing with what libCEED is doing with the context behind the scenes.

**Comment by jeremylt** [comment]
I was confused by the raw CeodVector sitting in the struct - that's not defined during JiT

**Comment by sebastiangrimberg** [comment]
Ah, I did not realize the context data for QFunctions was also being JiT'd, but I guess that does make sense. Can the member just be `CeedVector *` then, with a forward declaration of `CeedVector`? Or, I believe we already can just add the typedef that a `CeedVector` is really a pointer to a `CeedVector_private` and the compiler should be happy (since we never do anything in the QFunction with the CeedVector, only the data pointer)?

**Comment by sebastiangrimberg** [comment]
Again, if you have better ideas for how to accomplish this (or reasons to avoid it altogether and just use some `MAX_SIZE` constant for the maximum allowable size) I'd love to hear your ideas!

**Comment by jeremylt** [comment]
In Ratel we use fixed length arrays in the contexts since it's simple and a pretty small amount of waste compared to the number of quadrature points.

My immediate reaction is that I don't love defining symbols inside of JiT that cannot be actually used - I worry that it would be confusing for users. It also kinda breaks the idea that you can get the context data on the device and use it on the device or get the data on the host and use it on the host at any point in your code.

**Comment by jeremylt** [comment]
If it's a pure array of all one type, you can define it's length at runtime

**Comment by sebastiangrimberg** [comment]
Ah! Is this what `CeedQFunctionContextSetDouble` (and associated registration) does? That might be best, even if the context data isn't fully homogenous I can just store it in the first few entries as a floating point type and cast it back inside the QFunction.

But agree also that it's also possible the penalty of fixed size arrays is not noticeable. I'm just thinking of cases where we have something like 100s of parameters which need to be stored. Still much smaller than the number of quadrature points, though, you are correct.

**Comment by jeremylt** [comment]
The QFunctionContextRegister lets you label a part of the context data by name, and then you can update that part later by the name alone.
