### ISSUE TITLE
How to update a CeedVector of a CeedOperatorField?

### ISSUE THREAD

**Issue by bishtgautam** [CEED/libCEED#1403]
To update a time-varying boundary condition/source-sink term, I tried to update a CeedVector associated with a field in a CeedOperator. I did the following:

1. Obtained the field via `CeedOperatorGetFieldByName`
2. Obtained the CeedVector via `CeedOperatorFieldGetVector`
3. Finally, updated the CeedVector via `CeedVectorSetValue`

This procedure did not successfully update the CeedVector and I believe it is because the CeedVector obtained via `CeedOperatorFieldGetVector` has intent `out` and cannot be updated. I didn't find a corresponding `CeedOperatorFieldSetVector` function. How can I update a CeedVector associated with a field in a CeedOperator?

**Comment by jedbrown** [comment]
Are you saying that `CeedVectorSetValue` did not set the value or that an operator that you expected to write into it did not?

Generally, there is `CeedOperatorSetField` if you really want to change the vector, or you can use `CeedVectorSetArray` to have the operator read/write from unowned memory.

**Comment by bishtgautam** [comment]
The `CeedVectorSetValue` correctly sets the value when the CeedOperator is created. However, when I tried to update the CeedVector after the operator is created via `CeedOperatorGetFieldByName`+`CeedOperatorFieldGetVector `+`CeedVectorSetValue`, it didn't work.

Here is the code

- The field `q_dirichlet` from a CeedOperator is accessed at https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L320-L332
- The CeedVector is accessed at https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L342
- The values in the CeedVector are being updated via `CeedVectorGetArray/CeedVectorRestoreArray` at https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L342

The field `q_dirichlet` is an input field:
- The QFunction: https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L159
- The CeedOperator: https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed.c#L242

**Comment by jeremylt** [comment]
In what way didn't it work? Did you not see the updated values inside of the QFunction?

**Comment by bishtgautam** [comment]
Yes, I didn't see the update values inside the QFunction.

**Comment by jeremylt** [comment]
No change in values or not the values you expected? No change in values whatsoever seems unlikely, but would indicate that you're changing that vector somewhere else as well. Values being different than you expected would indicate that you are using a different ordering in that vector than your ElemRestriction expects.

**Comment by bishtgautam** [comment]
I get no change in value. I will debug this more and report back. Thanks.

**Comment by jeremylt** [comment]
Sounds good. I can help more actively after Thanksgiving if it's still acting up.

**Comment by bishtgautam** [comment]
@jedbrown @jeremylt, One followup, can the CeedVector that is obtained via `CeedOperatorFieldGetVector` be modified?

**Comment by jeremylt** [comment]
You can change the contents of the vector but you cannot change which vector is being used

**Comment by jeremylt** [comment]
You can change the contents of the `CeedVector` but cannot change which `CoedVector` the field is using

**Comment by bishtgautam** [comment]
In other words, the QFunction will not see the updated contents of the CeedVector. Is that correct?

**Comment by jeremylt** [comment]
No. The contents of the vector are updated. If those contents are not updated anywhere else, then the QFunction will get the updated contents

**Comment by bishtgautam** [comment]
It turns out that I wasn't updating the correct indices of the CeedVector. e.g. In a domain consisting of 2746 grid cells with only 2 grid cells on which a boundary condition was being applied, I had mistakenly assumed that the `CeedVector` was of size 2 (when the correct size of the CeedVector was 2746). After correctly updating the CeedVector, the QFunction does get the updated values. (https://github.com/RDycore/RDycore/pull/113/files#diff-c3a185b2fadbb0e6b4e9bc0014b9c35d654022fd86f4ceee6ca26644a5a51738L349). Thanks for your help.

**Comment by bishtgautam** [comment]
@jeremylt One follow-up question regarding an output field. I was using an output field for accumulating fluxes in a QFunction. However, I noticed that in some cases the values accumulated in that output field are not correct. Can I expect that libCEED will allow users to accumulate values in an output field? Or, the memory for the output field can change between calls to QFunctions, so one cannot accumulate values?

- An output field: https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed_impl.h#L110
- The accumulation of values in that output field https://github.com/RDycore/RDycore/blob/main/src/swe/swe_ceed_impl.h#L126

**Comment by jeremylt** [comment]
`CeedOperatorApply` overwrites all outputs. `CeedOperatorApplyAdd` sums results into the output vector. Passive fields are always overwritten.
