### ISSUE TITLE
Scalar element-wise constant data for QFunction

### ISSUE THREAD

**Issue by sebastiangrimberg** [CEED/libCEED#1416]
It seems like all the inputs to a QFunction need to use the same quadrature "space" (they can have different numbers of components but always have an entry for each quadrature point). Is there capability for having some scalar inputs to a QFunction which are element-wise constants? It seems wasteful to have to provide them as replicated values at each quadrature point, but maybe it's generally assumed that shouldn't be a concern? Thanks!

**Comment by jeremylt** [comment]
We haven't run to a memory limitation yet related to this.

You can get behavior like what you describe by making a basis that has 1 dof and a compatible quadrature space.

**Comment by sebastiangrimberg** [comment]
Ah, I had not thought of that! I agree the total memory savings should not be much relative to the other QFunction fields, I was just curious mainly. Thanks!
