### ISSUE TITLE
Fluids naming consistency

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1417]
(More to be added as I find them, just making one central location for them so I don't forget).

- Use `qfctx` for `CeedQFunctionContext` objects, and `ctx` for the structs themselves
  - The inconsistent format is to use `context` for `CeedQFunctionContext` and `ctx` for the structs

**Comment by jrwrigh** [comment]
Another misc task: Move the comments describing functions in `navierstokes.h` into docstrings in the function. Doesn't make much sense to have them in the header file, especially when their redundant to the name of the function (yay for good function names though!).

**Comment by jeremylt** [comment]
This would probably be transferred to the HONEE repo?

**Comment by jrwrigh** [comment]
Yeah, that works.

**Comment by jrwrigh** [comment]
https://gitlab.com/phypid/honee/-/issues/9
