### ISSUE TITLE
Development Plan

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#142]
I have laid out some efforts that we are working on and some suggested smaller PRs that would get us there. My intention is to coordinate our efforts and foster smaller, less disruptive, faster PRs. I really would appreciate discussion on this.

# Combined List of Current Thrusts

Thrust: Performant backends
PRs / Tasks:
- ~~Merge CUDA backend~~ done
- Document performance results to share with apps
- Compare with libParanumal

Thrust: QFunction Gallery
PRs:
- Add QFunction names
- Add QFunction lookup from gallery

Thrust: Create libParanumal Backend
PRs:
- ~~Add non tensor bases to interface~~ done
- Add non tensor bases to GPU backends
- Add QFunction names/QFunction gallery
- ~~Add GPU template backend that dispatches to OCCA~~ done, can delegate to any backend
- Add libParanumal backend

Thrust: Provide easy way to benchmark performance
PRs / Tasks:
- ~~Make sure PETSc BPs are performant on CPUs~~ done
- Make sure PETSc BPs are performant on GPUs
- ~~Import running and plotting scripts from CEED/benchmarks repo~~ done

Thrust: First wave of libCEED app integration
PRs / Tasks:
- Add libCEED support in MFEM
- Add libCEED support in Nek5000
- Develop NS/more sophisticated apps than the BP based on libCEED

Thrust: More Compelling Examples
- ~~Add Navier-Stokes example in PETSc~~ done
- Update example to handle more complex boundary conditions
- Update example to handle more complex meshes with DMPLEX
- Add face integrals to interface
- Add face integrals to backends
- Update example to handle even more complex boundary conditions

Thrust: Single Source QFunctions
PRs:
- Add common CUDA/OCCA/CPU QFunction file

Thrust: Strengthen Test Suite
PRs:
- ~~Add whitelist/blacklist~~ done
- ~~Add Nek CI~~ done
- Add MAGMA CI
- Add GPU CI
- ~~Add OSX CI~~ done
- Add GPU versions of tests?

Thrust: Support Complex Topology
PRs:
- ~~Add non tensor bases to interface~~ done
- Add non tensor bases to *more* backends
- Add non conforming mesh restrictions
- ~~Add composite operators to interface~~ done

Thrust: Documentation Improvement
PRs:
- ~~Document BP examples with mathematical formulation of problem~~ done

Thrust: API Consistency
PRs:
- ~~Update for variable consistency across functions/objects~~ done

@tzanio @jedbrown @v-dobrev @camierjs @stomov @Steven-Roberts @dmed256 @thilinarmtb

**Comment by tzanio** [comment]
Thanks for adding this @jeremylt. I think this is a productive way to have the discussion.

GitHub also has the https://github.com/CEED/libCEED/projects and https://github.com/CEED/libCEED/milestones features that could be useful to organize these.

**Comment by tzanio** [comment]
I will add a few other thrust to the list:

Thrust: Provide easy way to benchmark perfomance
PRs / Tasks:
- Make sure PETSc BPs are performant on CPUs and GPUs
- Import running and plotting scripts from CEED/benchmarks repo

Thrust: Performant backends
PRs / Tasks:
- merge CUDA backend
- document performance results to share with apps
- compare with libParanumal

Thrust: first wave of libCEED app integration
PRs / Tasks:
- add libCEED support in MFEM
- add libCEED support in Nek5000
- develop NS/more sophisticated apps than the BP based on libCEED

**Comment by tzanio** [comment]
From my perspective, the thrusts priority is:
1. Performant backends
2. libParanumal Backend
3. first wave of libCEED app integration
4. Provide easy way to benchmark performance
5. QFunction Gallery
6. Support Complex Topology
7. Strengthen Test Suite
8. Single Source QFunctions

**Comment by v-dobrev** [comment]
These are all good tasks/goals. Except prioritization, what specifically would you like to discuss about them? Assignments?

**Comment by v-dobrev** [comment]
It will be good to identify dependencies - it provides some natural prioritization. For example "merge CUDA backend" depends on "Add common CUDA/OCCA/CPU QFunction file" and "Add whitelist/blacklist".

**Comment by jeremylt** [comment]
For everyone's visibility, @valeriabarra and I are working on a demo NS solver that will cut across several of these thrusts: first wave integration, benchmarking performance, performant backends, complex topology (eventually).

@v-dobrev, I'd like to talk about what efforts I'm forgetting to mention and what are the best small PRs that we can break this down into. I also wanted to ID common effort so we could streamline/coordinate. - And you just commented about that :)

@tzanio, I'd personally prioritize strengthening the test suite higher. I know that in my work having MAGMA CI would significantly speed me up.

**Comment by tzanio** [comment]
@jeremyltm and others  -- can you add your prioritization in the table below?

| Thrust | Tzanio |
| --- | --- |
Performant backends | 1 |
libParanumal Backend | 2 |
First wave of libCEED app integration | 3 |
Provide easy way to benchmark performance | 4 |
QFunction Gallery | 5 |
Support Complex Topology | 6 |
Strengthen Test Suite | 7 |
Single Source QFunctions | 8 |

**Comment by YohannDudouit** [comment]
I agree with @v-dobrev , I thought that "QFunction Gallery" was required to have GPU kernels, so we can't have "libParanumal Backend" and GPU "Performant backends" before, am I wrong?

**Comment by jedbrown** [comment]
Is it valuable to keep this "meta issue" open versus appropriately tagging actual issues? If not, let's close this.
