### ISSUE TITLE
Setting up Travis CI with OCCA staging branch

### ISSUE THREAD

**Issue by dmed256** [CEED/libCEED#149]
Regarding https://github.com/libocca/occa/issues/198, would you guys be open to adding an extra Travis CI job that pulls OCCA from the `staging` branch?

Ideally all commits in OCCA should be going from either

- `staging` &rarr; `master`
- `branch` &rarr; `staging` &rarr; `master`

allowing us to hopefully catch issues before I merge things to `master`. If yes, I'll setup a PR for this

**Comment by jedbrown** [comment]
We could do that, but what about having OCCA CI run libCEED tests instead. Seems like it would out the info you want in a more useful place.

**Comment by dmed256** [comment]
That makes more sense, thanks!
