### ISSUE TITLE
CI Use --with-strict-petscerrorcode

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1522]
We should check that all our examples build fine with `--with-strict-petscerrorcode` then add that to the configurations for the CI builds of PETSc

**Comment by jrwrigh** [comment]
Confirmed that they all pass locally for me.

**Comment by jeremylt** [comment]
Updated on Noether, CI passing on re-run

**Comment by jrwrigh** [comment]
Annoyingly, the config flag apparently doesn't automatically catch this: https://github.com/CEED/libCEED/blob/47823346d50250045ce3eaaaa305de645045a703/examples/fluids/src/strong_boundary_conditions.c#L87

Though somehow `clangd` does recognize the issue:
> Ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]

Maybe we need to add an extra warning flag to our Makefile?
