### ISSUE TITLE
Handling or preventing `CeedInt` overflow

### ISSUE THREAD

**Issue by sebastiangrimberg** [CEED/libCEED#1526]
This issue comes up sometimes when debugging very large problems, where the global size of a quadrature data vector (`num_elem * elem_size * num_comp`) is greater than 2^31 even if none of the individual entries are. This leads to overflow, for example when indexing into vectors in `CeedElemRestrictionApplyStridedNoTranspose_Ref_Core`. I'm not sure if element restriction is the only place these overflows can occur, but my guess is that they likely happen elsewhere as well.

I know the code uses the `CeedSize` type for vector lengths avoids overflow. I'm wondering if indexing into a vector of length > 2^31 is supposed to be supported/should be supported or if this is something we should just write off as a bad idea? I guess it would involve just promoting some of the large values like `num_elem` to `CeedSize` so the index is calculated as a `CeedSize`. Thanks in advance!

**Comment by jeremylt** [comment]
Yeah, vector lengths are supposed to be fine when > 2^31. `CeedSize` wasn't in the library originally, so we're still catching places where promotion is wrong.

**Comment by jeremylt** [comment]
I don't think `num_elem` should need to be a `CeedSize`, but all the for loops in `ceed-ref-restriction.c` should probably be using `CeedSize` instead of `CeedInt`.

**Comment by sebastiangrimberg** [comment]
That makes sense. This seems like these changes might have to permeate quite deep to get everything to work. I think on the CPU a similar `CeedSize` promotion would be needed for some/all of the operator application loops over elements too (correct me if I am wrong). Is the wider type indexing overhead a concern or has that been discussed previously? It looks like diagonal and full assembly already are correct in `ceed-preconditioning.c`.

Probably similar changes as `cuda-ref-operator-assemble.h` and `cuda-ref-operator-assemble-diagonal.h` with the `IndexType` macro would need to be made in all of the element restriction + basis kernels for the GPU, also.

**Comment by sebastiangrimberg** [comment]
Just 2^31 local nodes/quadrature points (the latter). It certainly isn't high priority since this is a pretty big scale for a single device/MPI rank but in the long run the robustness to handle these cases would be great to have. I can try to make an attempt at resolving some of the loops when I get some time.

**Comment by jeremylt** [comment]
I have a guess at the root of the behavior you see.

@jedbrown we do have a logical inconsistency in the interface for creating restrictions
```
int CeedElemRestrictionCreate(Ceed ceed, CeedInt num_elem, CeedInt elem_size, CeedInt num_comp, CeedInt comp_stride, CeedSize l_size,
                              CeedMemType mem_type, CeedCopyMode copy_mode, const CeedInt *offsets, CeedElemRestriction *rstr) 
```

> All offsets must be in the range `[0, l_size - 1]`.

`l_size` is a `CeedSize` but the `offsets` are `CeedInt`. So we can have invalid values in `offsets` when `l_size` is greater than the max `CeedInt`

**Comment by sebastiangrimberg** [comment]
Yep that's one. This happens even in the strided case, too:

```
vv[e * elem_size * num_comp + (k * elem_size + n) * block_size + j - v_offset] =
  uu[n + k * elem_size + CeedIntMin(e + j, num_elem - 1) * elem_size * num_comp];
```

All of the indexing here is done with `CeedInt`s.

**Comment by jeremylt** [comment]
Yeah, the strided case should be easy to fix with some casting at least.

**Comment by jedbrown** [comment]
clang-tidy [`bugprone-too-small-loop-variable`](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/too-small-loop-variable.html) can help ensure we've found all the problematic places.

Our logic here was that while L-vectors don't need to be more than 2B in general use, we use `CeedVector` as a container (since it's GPU-aware) for matrix assembly (both in Q-space and as concatenated element matrices with L-vector index arrays). Those blow over 2B quite easily. For offset arrays, there is a nontrivial performance penalty to making `CeedInt` use `int64_t` -- those are problem-sized arrays. If we need 64-bit offsets, I would add a new interface and distinguish them internally (which would mean making some routines generic over the indices).

**Comment by sebastiangrimberg** [comment]
I think this is the regime to which I am referring. I think my E-vectors using offset restrictions are fine with 32-bit indices, the problem is quadrature data which has O(100) more entries and clears 2B very quickly. Thus it might be enough to just fix element restriction indexing without adjusting the offset types.

**Comment by jedbrown** [comment]
Thanks. This has been tested a fair amount using the GPU backends, but I suspect some of this indexing has fallen through the cracks on CPU backends (where most of us use more MPI processes, and thus have much smaller subdomains). Let's see how much the clang-tidy check can identify these.
