### ISSUE TITLE
Create `CeedOperatorFieldGet*Read` routines with `const` parameters

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1639]
I think on the existing `CeedOperatorFieldGet*` probably aren't appropriate for "normal" uses by end-users; Those objects shouldn't be editable (or at least Destroyable), but the lack of a `const` qualifier on the parameters means you can. See [HONEE MR](https://gitlab.com/phypid/honee/-/merge_requests/27#note_2014079011) for example of accidentally Destroying something gotten from `CeedOperatorFieldGet*`.

Adding `const` qualifiers would break existing code unfortunately, so assuming that's a non-starter, maybe we could implement "read" versions of the Getters?
i.e.:
```c
CEED_EXTERN int CeedOperatorFieldGetElemRestrictionRead(CeedOperatorField op_field, const CeedElemRestriction *rstr);
CEED_EXTERN int CeedOperatorFieldGetBasisRead(CeedOperatorField op_field, const CeedBasis *basis);
CEED_EXTERN int CeedOperatorFieldGetVectorRead(CeedOperatorField op_field, const CeedVector *vec);
CEED_EXTERN int CeedOperatorFieldGetDataRead(CeedOperatorField op_field, const char **field_name, const CeedElemRestriction *rstr, const CeedBasis *basis,
                                         const CeedVector *vec);
```

**Comment by jrwrigh** [comment]
Yeah, I think adding the Restore-half of the Get methods works well too.

**Comment by jeremylt** [comment]
We'd have to spin up a companion PR to MFEM since it will disrupt them a little, but it feels like the "right" way to do that interface.

**Comment by jeremylt** [comment]
Ugh, this becomes much messier that I hoped. There are 735 instances of `CeedOperatorFieldGet*` in the codebase, and updating the usage for OCCA is a hassle. This would help our Rust usage though, especially if we add `CeedOperatorRestoreFields`. This sorta has to be done in one big bite, so this branch is slow going.
