### ISSUE TITLE
Quid of the libCEED API for GPU

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#164]
Studying the implementation of Generic GPU kernels for MFEM, I wanted to reiterate my concerns for efficient GPU implementation in libCEED. Take what I say with a pinch of salt though as I might have overlooked many aspects of the problem.

If we take as a primary goal for efficient GPU backend: generating GPU code with performance close to [libParanumal](https://www.paranumal.com/). If I understand correctly libParanumal, the GPU kernels fuse `Prolongation`/`OperatorApply`/`Restriction`, so that the kernel only requires one memory swipe. Since the kernels are highly memory bound, reading and writing the data only once (all computation being hidden by memory transfers) gets close to the best achievable performance for partial assembly with sum factorization.
The libCEED approach is to decompose a kernel into `Prolongation`, `OperatorApply`, `Restriction`, and further decompose `OperatorApply` in `BasisApply`->`QFunctionApply`->`BasisApply`.
This decomposition provides a clear path on CPU for generic operators, we decided in libCEED to implement this genericity through dynamic linking of function pointers according to the intent of the user. This approach is reasonable on CPU since at this level of abstraction the function pointers and optimizations barriers created by them are not an issue.
However, for a GPU, a dynamic function pointer means a GPU kernel launch, and thus a memory swipe. A naive approach would thus result in five memory swipes (`Prolongation`->`BasisApply`->`QFunctionApply`->`BasisApply`->`Restriction`). Since these kernels are highly memory bound, the performance is directly proportional to the inverse of the number of memory swipes. This naive approach would thus result in the **best case scenario** in approximately 20% of the performance of libParanumal. On the other hand, an optimized approach would require to be at the highest level of abstraction of libCEED in order to perform only one memory swipe.
The problem when we implement kernels at the highest level of abstraction is that we loose all the generic decomposition of an operator that libCEED is trying to provide. GPU kernels become nothing more than a single function name that calls a kernel that has to be specialized for every operator desired by the users. This specialization of GPU kernels at the highest level of abstraction would result in a combinatorial explosion of the required GPU kernels.
Since this issue is in conflict with libCEED's primary goal of providing optimized generic operator specified by the user, this means that in order to get good generic GPU performance we need to be able to do code generation. The problem with this is that it seems to split the libCEED CPU and GPU API, and it is not trivial to see how to reunify them.

I personally see two possible path to make code generation and reunify the API. The first one is to generate a Cuda (or OCCA or whatever) source code file and then JIT compile it with [NVRTC](https://docs.nvidia.com/cuda/nvrtc/index.html) (This is partially the approach attempted in the [cuda branch](https://github.com/CEED/libCEED/tree/cuda/backends/cuda) of libCEED). We could provide `__device__` functions corresponding to the functionality decomposition of libCEED, that would be then assembled on the fly in a `String` in order to give this `String` to NVRTC and generate the GPU kernel operating at the same level of abstraction as libParanumal and hopefully have similar performance. This design could potentially generate all the desired libCEED functions keeping the C interface of libCEED intact. The `Create` functions would define which `String` to use to represent the device function of the kernel and generate a C function using NVRTC, and the `Apply` would just call this C function generated by NVRTC. However, in order to propose optimized functions working at higher level, we would need to be able to fetch lower level functions `String`s in higher level libCEED functions in order to assemble on the fly a higher level function with NVRTC, *e.g.* `CeedOperatorCreate` would need to fetch the `String` from `CeedBasis` and `QFunction` and compose them in one `String` in order to use it with NVRTC and generate the higher level function `CeedOperatorApply`. The last level of operator fusion might be the most challenging, *i.e.* fusing `Prolongation`/`OperatorApply`/`Restriction` as this requires a more tight coupling of algorithms. 

The second approach I see, which is more natural to me, is to use [Generic Programming](https://en.wikipedia.org/wiki/Generic_programming). Generic Programming existing both in C++ and Cuda through templates. Cuda kernels accepting templates, and NVRTC being able to JIT compile templated kernels. The approach would be to use template meta-programming techniques, namely [policies](https://en.wikipedia.org/wiki/Policy-based_design), as described in [Modern C++ Design by Alexandrescu](https://en.wikipedia.org/wiki/Modern_C%2B%2B_Design). The different policies corresponding to the orthogonal functionalities proposed by libCEED.The policy based design could be easily unified for CPU. The policy based design would though have to be written in C++, making the linking with C and Fortran a bit more challenging, but this could be solved with [Hourglass APIs](https://www.slideshare.net/StefanusDuToit/cpp-con-2014-hourglass-interfaces-for-c-apis).

I didn't mention an approach based on Object Oriented Programming, and especially virtual functions, since this present the exact same issues as the design with dynamic function pointers.

The `String` based and policy approaches would both present the same challenges as it would be very difficult to control *a priori* the quality of a generated kernel due to the difficulties to predict register usage, occupancy, memory spills, memory coalescing, etc... which can quickly turn a GPU kernel into garbage. Fortunately, the BK and BP problems would be here to the rescue to cover the most important cases.

Even though I prefer the policy based approach, I understand that for the project the `String` based approach might fit more our needs. In the case you see one of these two approaches promising, I would be happy to work on the chosen one.

**Comment by jedbrown** [comment]
Minor correction: `OperatorApply` contains restriction/prolongation.
Also note that a design goal of libCEED is to be able to select backends at run-time without being aware of them at compile time. Template metaprogramming breaks that abstraction. It is also significantly more difficult for non-experts to write and debug.

**Comment by YohannDudouit** [comment]
I realized that in the presence of `grad` evaluation my best performance achievable was off. Indeed, the output/input of grad evaluation is Dim time larger, so in the case of an un-fused 3D diffusion kernel that's: ` (1r) Restriction (1w) -> (1r) BasisApply (3w) -> (3r + 6r (for D)) QFunctionApply (3w) -> (3r) BasisApply (1w) -> (1r) Prolongation (1w) `, compared to the optimal workflow: `(1r + 6r) Operator (1w)`, That's `8/24=33%`, it means that the optimal performance of an un-fused diffusion kernel is 33% of the optimal performance of an optimal fused kernel.
Similarly, for a 3D mass kernel the maximum achievable performance of an un-fused kernel is `3/11=27%` of the optimal performance of a fused kernel.
And in the case of vectorial unknowns the performance cost is even higher: `12/60=20%` for vectorial isotropic diffusion, and `7/31=23%` for vectorial mass.
However, one could argue that it's over optimistic to fuse Prolongation/Restriction with the rest of the kernel, and that the performance of the Prolongation/Restriction operations on GPU is very uncertain due to the random memory access nature of these operations. But I still think that these numbers show the importance of having backends capable to fuse the different parts of an Operator in a minimal amount of GPU kernels.

**Comment by jedbrown** [comment]
Closing; please reopen if you think this discussion is unresolved/has actionable tasks.
