### ISSUE TITLE
Bug in diagonal assembly AtPoints with multi active fields

### ISSUE THREAD

**Issue by rezgarshakeri** [CEED/libCEED#1640]
The diagonal assembly at points has a bug. You can run this mpm mixed linear problem in [ratel](https://gitlab.com/micromorph/ratel/-/merge_requests/899) with `-pc_type svd` or using field split but with `-pc_type jacobi` it won't converge.

**Comment by jeremylt** [comment]
Honestly, I don't remember coding for multiple active fields so I'm surprised it tries. But it shouldn't be too hard to sort out

**Comment by jeremylt** [comment]
Ohh, the e-vec size is different in mixed between active fields. I should be able to fix that without too much hassle.
