### ISSUE TITLE
CeedGetScratchVector

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1670]
New API that lets a Ceed hold scratch vectors, such as for E-vecs.

Probably best to make a small object held by the Ceed that holds the scratch vectors

Return the smallest vec that's big enough

* CeedGetScratchVector
* CeedRestoreScratchVector
* CeedScratchCreate
* CeedScratchDestroy

Should only be in the backend API

**Comment by jrwrigh** [comment]
See `DM{Get,Restore}WorkArray` for similar functionality there.

**Comment by jedbrown** [comment]
Also, `DM{Get,Restore}{Local,Global}Vector`, though that implies the size. If you put this cache on the `Ceed`, the interface will need to specify the size and you'll need to choose between handing out a big vector (temporarily resized down) for a smaller request or to make a new one to keep the big one available for possible future requests.

**Comment by jeremylt** [comment]
For now, since this would only be used for e-vectors in CeedOperatorApply my plan is to keep with a simple strategy of returning any work vector that meets the requirements (not to say that's all it will remain limited  to)
