### ISSUE TITLE
Adding Device memory tests for CeedVector

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#176]
I think it's time to think about basic tests on vectors using CEED_MEM_DEVICE.
I was thinking of a test of the kind:
```
int main(int argc, char **argv) {
  Ceed ceed;
  CeedVector x;
  CeedVector y;
  CeedInt n;
  CeedScalar a[10];
  const CeedScalar *b, *c;

  CeedInit(argv[1], &ceed);
  n = 10;
  CeedVectorCreate(ceed, n, &x);
  CeedVectorCreate(ceed, n, &y);
  for (CeedInt i=0; i<n; i++) a[i] = 10 + i;
  CeedVectorSetArray(x, CEED_MEM_HOST, CEED_USE_POINTER, a);
  CeedVectorGetArrayRead(x, CEED_MEM_DEVICE, &b);
  CeedVectorSetArray(y, CEED_MEM_DEVICE, CEED_COPY_VALUES, b);
  CeedVectorRestoreArrayRead(x, &b);
  CeedVectorGetArrayRead(y, CEED_MEM_HOST, &c);
  for (CeedInt i=0; i<n; i++) {
    if (c[i] != 10+i)
      printf("Error reading array c[%d] = %f",i,(double)c[i]);
  }
  CeedVectorRestorArrayRead(y, &c);
  CeedVectorDestroy(&x);
  CeedVectorDestroy(&y);
  CeedDestroy(&ceed);
  return 0;
}
```
This raised a question to me, what is the expected behaviour in a case like:
```
  CeedVectorSetArray(x, CEED_MEM_HOST, CEED_USE_POINTER, a);
  CeedVectorGetArrayRead(x, CEED_MEM_DEVICE, &b);
  CeedVectorSetArray(y, CEED_MEM_DEVICE, CEED_USE_POINTER, b);
```
Is the ownership model supposed to handle that this is not a licit use of the pointer `b`?

**Comment by jeremylt** [comment]
The libCEED vectors x and y do not know about each other's private data, so I am not sure how we would do anything about this. In this case the user has requested read only access pointer and provided that pointer to a vector that may modify the data. I don't know that we can stop the user from wilfully ignoring the fact that they requested read only access without requiring that the backends make possibly very expensive copies of the data.

**Comment by YohannDudouit** [comment]
Regarding the test itself, do you have any remarks? Other tests ideas?

**Comment by jeremylt** [comment]
Than seems like a good test. Maybe also a test where data is set on host, changed on device, and then checked on host?

**Comment by YohannDudouit** [comment]
I don't see any way to change values on device with the vector interface since `SetValue` does not take a `CeedMemType` parameter. We could imagine an "advanced" version of `SetValue` with a `CeedMemType` parameter though. This could reveal especially useful if we want to unit test more extensively `CEED_MEM_DEVICE` usages.
It could also be useful in later benchmarking tests of basic operations.

**Comment by jeremylt** [comment]
I suppose that case would be checked by Basis Apply and QFunction apply already.

I think the user shouldn't care where SetValue is applied, as that should be up to the backend

**Comment by jedbrown** [comment]
Your example will raise a warning due to passing the `const` pointer as non-const. (The C type system can't enforce this properly, but it does generate the warning in this instance.)

**Comment by jeremylt** [comment]
PR #177
