### ISSUE TITLE
Fortran pointers address don't match the given one.

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#184]
I have issues with the Fortran Vector tests because I check that the returned pointer in `VectorRestoreArray` is actually one the pointer that is used by the Vector, unfortunately this is not the case. I can disable this check, but my feeling is that the problem comes from the Fortran interface as my check is correct and meaningful.

**Comment by jeremylt** [comment]
The core of this is the difference in how Fortran 77 and C90 handle 'pointers' to arrays. 

In the C interface, the pointer given to the user in GetArray or GetArrayRead is returned to the backend in the arugment list for RestoreArray or RestoreArrayRead.

In the Fortran interface, we do not have the ability to change the address of the array passed in. We instead pass in a temporary C pointer and then find the offset between the pointer in Fortran and the temporary pointer in C. This temporary C pointer is then dropped as the only relevant thing for the Fortran user is the offset.

Most backends set the returned pointer to NULL and the Fortran zeros the offset for RestoreArray or RestoreArrayRead.

Personally, I think this is adequate. The zeroing of the offset/setting the pointer to NULL is more of a aid to the user than actual protection for the memory as the user can always make a copy of the offset/pointer before returning it, so getting the 'right' pointer back doesn't help the library. Second, Fortran never has the pointer directly to the array, so the relevant vaue is the offset for the Fortran interface. Third, if write access was granted, then you already know which pointer (host or device) was returend and if read access was granted, then all that matters is that the number of readers goes back to zero before attempting to write again.

**Comment by YohannDudouit** [comment]
I still think that there is a design flaw. If there is a `RestoreArray` backend function it's because the backend might be doing something more than just `*array=NULL` otherwise it could solely be done by the libCeed interface. This pointer is unfortunately invalid, so just doing `*array=NULL` might have unexpected consequences, and using this pointer for backend purpose would also result in an error. So if we want to keep this invalid pointer by design necessity, we might want to remove `RestoreArray` and `RestoreArrayRead` from the backend functions.

**Comment by jeremylt** [comment]
The Fortran pointer is not mutable, so `*array=NULL` should have no effect. I've run some small tests and had no problems.

I think the RestoreArray and RestoreArrayRead can have backend utility, so we should keep it, but I agree that this function doesn't really need the `array` argument. The setting `*array=NULL` can be done at the interface level.

**Comment by YohannDudouit** [comment]
I don't think that the C compiler is aware in any way that the value originally was from a non mutable Fortran pointer, this information is lost at this point, whatever is at address `*array` gets the value `NULL` or SegFaults if the program wasn't allowed to write in this memory space, this is a dangerous behaviour. This is actually intriguing that it doesn't result in bugs in some ways. Setting a random memory address to `NULL` shouldn't be without consequence.

If we keep the `array` argument then we should specify what is the expected behaviour when its value is different from the stored data pointer.

**Comment by jeremylt** [comment]
It isn't totally random, its the pointer to the array the fortran program declared. But in my tests the array still seems usable after RestoreArray, so I'm not 100% sure why.

I don't know that there is any reason to care if the value agrees or not, as the user may have done pointer arithmatic or some other modification to their pointer.

**Comment by jedbrown** [comment]
We have no way to enforce that the caller doesn't continue to manipulate
that pointer (in violation of a contract that the compiler is unaware
of), but it is important to inform Ceed that the access period is
complete and it is free to begin migrating updates to a device or assume
that cached quantities remain valid until the next mutable access, for
example.

**Comment by jeremylt** [comment]
Exactly, so I don't see a need to force the Fortran interface to store and pass back the pointer. The salient point is that the return was called. I don't think any changes are needed.

**Comment by YohannDudouit** [comment]
I don't think it's a good approach to migrate data during the `Restore`, I think it's always better to do it in the `GetArray`.
@jeremylt @jedbrown Do we agree that we should remove `array` from the backend `Restore` as it can be meaningless due to the Fortran interface?

**Comment by jeremylt** [comment]
See PR #210
