### ISSUE TITLE
clang-tidy

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#193]
clang-tidy path/to/source.c -- -Iinclude

highlights a number of places where we forgot to check return values or made invalid assumptions. There's also noise about issues that it can't show statically are actually fine, but it would be worth either adjusting the code to help the static analysis or disabling those checks at the finest possible granularity.

**Comment by jeremylt** [comment]
I did a first past to handle the return values and some of the faulty logic. It still complains about `strcpy` and some of `ceed.c` and `ceed-vec.c`.

**Comment by jedbrown** [comment]
Would be good practice to avoid `strcpy` anyway.

**Comment by jeremylt** [comment]
Good point. There will be a follow-up PR to do more, I just wanted to make sure we get the easiest parts before v0. 5.

**Comment by jeremylt** [comment]
Ok, the `strcpy`issues have been resolved. All that remains is "noise about issues that it can't show statically are actually fine".
