### ISSUE TITLE
Linking BLAS

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#199]
On CU Summit using the Intel compilers, the libXSMM backend requires linking against MKL instead of BLAS. Currently this requires a manual Makefile edit.

**Comment by alheinecke** [comment]
you can build LIBXSMM with BLAS=0 then this should go away, of course when using libxsmm_dgemm and JIT is failing, then there is no longer a call.

@hfp if this is bad, then we should add 3 nested loops.

Alex

**Comment by hfp** [comment]
> libXSMM backend requires linking against MKL instead of BLAS

Let me restate, what you wrote:

1. Linking any BLAS (for instance OpenBLAS) is not "good enough" (MKL seems a hard dependency).
2. You did not intend to remove BLAS as a dependency (which is what Alex suggested aka `BLAS=0`).

Can you confirm?  If (1) is true, it is a bug and I will definitely fix it i.e., we want LIBXSMM to have no dependency a specific LAPACK/BLAS library (any BLAS library should be fine).  So, (2) is not our intended way to fix (1) but allows to remove LAPACK/BLAS dependency if a fallback is not needed.

**Comment by jeremylt** [comment]
To clarify, I don't see this as a LIBXSMM issue. For whatever reason, CU Summit's linking against BLAS isn't working quite right so I'm linking against MKL instead. 

I'd prefer not to specify to our users any particular way to make libraries that our backends may use, so I'd prefer not to insist that our users make LIBXSMM with `BLAS=0`.

I think this is a libCEED Makefile fix where I link against BLAS *or* MKL. I don't think a fallback is needed, so it doesn't change our performance at all but rather the ease of building our software.

**Comment by hfp** [comment]
Thanks!

Here are some comments:

* `MKL=0` can force using another LAPACK/BLAS library (LIBXSMM's Makefile is supposed to work with MKL, OpenBLAS, or RefLapack/RefBlas with preference in the order listed). If RefBLAS is preferred over OpenBLAS, `OPENBLAS=0` is similiar to `MKL=0`. There are more keys to help picking up BLAS on systems with more specific directory layout. This is only about convenience with out-of-the-box builds, libxsmm actually relies only on `dgemm_` and `sgemm_`symbols (not a specific BLAS implementation).
* I found libCEED is missing to link against Pthreads (`-pthread` for CC/LD step). At least LIBXSMM induces this dependency. One can also rely on pkg-config to manage what to link else if libxsmm is linked: [https://libxsmm.readthedocs.io/#link-instructions](https://libxsmm.readthedocs.io/en/latest/#link-instructions)
* libCEED could consider `libxsmm_source.h` aka [header-only](https://libxsmm.readthedocs.io/en/latest/#header-only) to get rid of making LIBXSMM - just in case somebody does not like to build libxsmm as a separate library/dependency.

**Comment by jedbrown** [comment]
@jeremylt We use `pkg-config` for libCEED examples and would prefer to use it for libxsmm than to add new options to libCEED. That said, I notice that `pkg-config --libs libxsmm` is not sufficient (BLAS is still needed) and there is no `libxsmmnoblas.pc`. What does libxsmm recommend a downstream library do?

**Comment by hfp** [comment]
> I notice that `pkg-config --libs libxsmm` is not sufficient (BLAS is still needed)

True! However, I really want to keep things independent of a specific BLAS library. There is no general pkg-config for BLAS to rely on, and I cannot put something into our `.pc` files that would depend on the system where the `.pc` files are generated on (since these files may be upstreamed/packaged).

> there is no `libxsmmnoblas.pc`

The next release will generate a `.pc` file for libxsmmnoblas. Should be soon in our master revision!

**Comment by hfp** [comment]
I realized that above comment can be misunderstood. The disadvantage of generating a `.pc` file for the BLAS library found during LIBXSMM's build phase is that LIBXSMM's libraries are still good for any other LAPACK/BLAS...

**Comment by jeremylt** [comment]
@jed, I merged the flag option as a temporary workaround until we work out something better.

I must admit, my Make knowledge isn't a good as I would like. Would this `libxsmmnoblas.pc` allow the user build the library normally and use `pkg-config --libs libxsmm` to indicate that we are not using the BLAS dependency?

**Comment by jedbrown** [comment]
^ Tagged the wrong Jed.
It would allow you to `pkg-config --libs libxsmmnoblas` to link a version of libxsmm that does not fall back to using BLAS, thus doesn't need the user (at some level) to link BLAS.
