### ISSUE TITLE
Makefile Generates Stray File

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#200]
The Makefile now generates `-.d`, which is a stray, empty file. It does it on `make` and `make clean`.

**Comment by jedbrown** [comment]
It's produced by this line
```
AVX := $(shell $(CC) $(CFLAGS) -v -E - < /dev/null 2>&1 | grep -c avx)
```
where `CFLAGS` includes `-MMD`, which writes a makefile dependency for the input source `-`.

**Comment by jeremylt** [comment]
The AVX information would be in the OPT flags, so I switched this line to using just the OPT flags rather than the full set of CFLAGS.
