### ISSUE TITLE
Makefile Valgrind Check Error

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#253]
On Cori and Theta we get the error message:

```
fatal error: valgrind/memcheck.h: No such file or directory
 #include <valgrind/memcheck.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

We need to rework the Valgrind check in the Makefile. The headers are only included in a 'development' or 'debugging' install of Valgrind, but the check currently looks for any version of Valgrind.

**Comment by jedbrown** [comment]
Resolved by #258.
