### ISSUE TITLE
Update Benchmark Plotting Scripts

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#265]
The postprocessing scripts should be updated to use a Pandas dataframe and the BP file should be updated to output more complete documentation of the parameters.

Eventually, it would be good to update the benchmarks repo with our work on improving the postprocessing scripts.

**Comment by valeriabarra** [comment]
Yeah there are also some other things that I didn't get to improve in PR #263.
1) there is another occurrence of 'q= p + %i+ ' on line 146 for the legend in the file `postprocess-plot.py`. That case didn't occur in my testing. 
2) now there is the variable `test_required_examples='petdc-bps' ` assigned in the file `petsc-bps.sh` that eventually creates the title of the plots with "petsc-bps", regardless of which one it is. I wasn't sure now that we have one single script for all petsc-bps how to handle this situation for this variable (perhaps with a list?)
