### ISSUE TITLE
Can't create C++ backend

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#271]
I can't create a C++ backend because `ceed-backend.h` includes the `restrict` keyword which is C but not C++. Should we remove the `restrict` keyword from `ceed-backend.h`?

**Comment by jedbrown** [comment]
We can define `CEED_RESTRICT` to be `restrict` for C99 and `__restrict` (or blank) depending on what C++ supports. Or remove it and create `restrict` pointers within the backends (because `restrict` enables some optimizations that would not otherwise be safe).

**Comment by YohannDudouit** [comment]
I'll remove `restrict` in my branch for now, we'll take a decision when merging this branch.
