### ISSUE TITLE
make install targets

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#28]
Install to prefix, recognize `DESTDIR`, install `ceed.h` header plus library. Also install Fortran components if applicable (cf. #19).

**Comment by acfisher** [comment]
Alright the latest passed the prefix onto the DESTDIR and installs the .h file.  I'm not sure I know what you mean about the fortran components.

**Comment by jedbrown** [comment]
The Fortran PR hasn't been merged yet.  When I say we should add 'make
install', I mean that this belongs in libceed (this is my job unless you
want to look at it), not in spack.

**Comment by acfisher** [comment]
Oh, I hacked around the lack of install in the makefile.with spack.  Let me know when you pit the new target in there and I'll is it.

**Comment by acfisher** [comment]
Err fix it
