### ISSUE TITLE
Memcheck Backend - Add Check

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#280]
If we go to a QFunction format that independently describes data stride and number of quadrature points, we should add a check in the memcheck backend or a new backend that verifies that user qfunctions are not mixing up N and Q.

**Comment by jeremylt** [comment]
This is no longer consistent with our current qfunction approach. @jedbrown @YohannDudouit do you still see value in separating the data stride and number of quadrature point parameters?

**Comment by jedbrown** [comment]
Not at this time unless @YohannDudouit has reservations about inlining capability for CUDA.
