### ISSUE TITLE
Update CPU Grad for Colocated Quadrature 

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#287]
As I mentioned in before we merged #282, I should update the CPU BasisApply for CEED_EVAL_GRAD when p=q to skip the unnecessary identity interpolation. This will improve our performance in cases such as BP 5/6. I can also include a check to substitute CEED_EVAL_NONE for CEED_EVAL_INTEP in this case. 

Thank you @fischer1 for reminding me.

I should be able to find a quick hour to fix this during this week.

**Comment by jeremylt** [comment]
@YohannDudouit this is probably worth adding to the CUDA backends, especially if you add the colocated gradient.

**Comment by YohannDudouit** [comment]
I believe colocated works, it's `P1d>Q1d` that will require some work.

**Comment by jeremylt** [comment]
I know that the CUDA backends work fine when the DoFs are collocated with the quadrature points, but I thought that you hadn't yet used that fact to reduce the total number of tensor contractions executed to dim for a grad in that case, or used the factored grad matrix to drop from dim**2 to 2*dim tensor contractions for grad.
