### ISSUE TITLE
Poll - BP3-6 Geometric Factors

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#337]
Our storage of the symmetric matrix representing the geometric factors at the quadrature points in the libCEED examples is counter to what is typical to what you see in literature ([See Mandel–Voigt notation](https://en.wikipedia.org/wiki/Voigt_notation)). Does anyone have any strong opinions about changing to a more conventional notation?

I believe I've tagged everyone involved with the development of relevant libCEED examples for PETSc, MFEM, and Nek.

Please vote below if you want to keep the current layout or switch to something more conventional. I'll interpret non-replies as no opinion either way.

Context: https://github.com/CEED/libCEED/pull/311/files#r321438418

**Comment by valeriabarra** [comment]
To me it doesn't really matter, as long as whatever convention is chosen is accurately documented.

**Comment by jeremylt** [comment]
There does not seem to be strong opinions here, so I'll switch to using Voigt notation after #338 merges so we can merge #311.
