### ISSUE TITLE
Underinterpolation Support

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#349]
Add support for CeedBasis when Q<P:
- [ ] OCCA
- [x] CUDA
- [x] MAGMA

**Comment by v-dobrev** [comment]
Just curious: In what cases does Q<P make sense? For example, if you use Q<P for a mass matrix, the local mass matrix will not be full rank.

**Comment by jedbrown** [comment]
Restriction to a coarse grid in multigrid, for example.  Some would also say intentional underintegration, such as to mitigate locking for the volumetric term in displacement-only elasticity.

**Comment by abdelfattah83** [comment]
The MAGMA backend should work for Q<P. I have tested this only for few combinations of ex1-volume and ex2-surface in libCEED, and it produces the same output as cpu/self/ref. If there is a benchmark that evaluates this feature, we would be happy to try it out.

**Comment by jeremylt** [comment]
I believe this was taken care of in the big OCCA refactor.
