### ISSUE TITLE
Non-Tensor Basis Support

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#350]
Add support for non-tensor bases
- [x] OCCA
- [ ] CUDA Gen
- [ ] HIP Gen
- [x] MAGMA

**Comment by nbeams** [comment]
Non-tensor capability was added to the MAGMA backend with #424.

**Comment by jedbrown** [comment]
Cc: #1022

**Comment by jeremylt** [comment]
Part of https://github.com/CEED/libCEED/issues/839
