### ISSUE TITLE
MAGMA Basis Apply

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#368]
The new MAGMA basis apply should be switched to a switch statement rather than if statements. We only evaluate one CEED_EVAL_MODE, and a switch statement would ensure all cases are covered.

**Comment by nbeams** [comment]
With fa15ec8f7d4f1ef69240a20f8a2c96138385b2b4, we can close this now, right?

**Comment by jeremylt** [comment]
correct, thanks for reminding me
