### ISSUE TITLE
CEED_EVAL_WEIGHT in t20-qfunction.c

### ISSUE THREAD

**Issue by camierjs** [CEED/libCEED#40]
t20-qfunction.c passes CEED_EVAL_WEIGHT in the setup CeedQFunctionCreateInterior, but uses u[0][i] then in the function. Should I switch for the _INTERP field instead?

**Comment by jedbrown** [comment]
The right fix (for consistencies sake) would be to make the setup
function use u[4][i] and then call it appropriately.  This fragility
should go away in the active-passive refactor.

**Comment by jeremylt** [comment]
Addressed in PR #41

**Comment by jeremylt** [comment]
Closed by PR #41
