### ISSUE TITLE
Default behavior of libCEED operators

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#412]
The current behavior of libCEED operators is to apply an operator `A` using `=`, the standard behavior in MFEM is to use `+=` ( `y += Ax` instead of `y=Ax`). Would it be possible to reconsider the default behavior of libCEED operators?

**Comment by jedbrown** [comment]
Or even `y = scalar*y + A x`, though that clutters the user interface. Vector zeroing used to be fast, but I'm concerned about its latency cost on GPUs (moreso than the bandwidth cost at this stage).

**Comment by YohannDudouit** [comment]
Regarding the GPU backends, the cost of zeroing is relatively low. Besides, the `cuda-gen` backend for instance has to zero the vector before applying the operator anyway because it's using `atomicAdd` for the prolongation, thus it wouldn't impact performance at all for the `cuda-gen` backend. You can see the cost of zeroing here https://github.com/mfem/mfem/pull/866#issuecomment-546428334 where you see the zeroing kernel followed by the `+=` kernel.
However, it could be beneficial to add a new `OperatorAddApply` instead of replacing the current `OperatorApply`. The `cuda-gen` would only have to zero the vector and then use `OperatorAddApply` to implement `OperatorApply`. However, other previous backends would have to use a different prolongation kernel for performance reasons to implement `OperatorAddApply`, but I think that it is a relatively small amount of work, basically replacing `=` by `+=` (not even `atomicAdd`).

**Comment by jeremylt** [comment]
`OperatorApply` should default to a wrapper for `OperatorAddApply` (Not my favorite name, but not sure what else to call it) where the interface zeros `v` first. On this CPU side this would be easy to add.

**Comment by jedbrown** [comment]
I'm fine with that change.
