### ISSUE TITLE
AssembleLinearQF/Op Fallback

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#425]
The `AssembleLinearQF/Op` fallback is failing. I want to provide a basic version of `CeedAssembleLinearQFunction`, `CeedAssembleLinearOperator`, and `CeedOperatorCreateFDMElementInverse` to get some preconditioning functionality for all backends.

Unfortunately, the CUDA backends seem to permute their vectors in some fashion, perhaps by blocksize? It looks like we have some sort of permutation along the lines of [elem1field1, elem2field1, elem1field2, elem2field2, ...] rather than [elem1field1, elem1field2, elem2field1, elem2field2, ...]. Am I reading that right? Is there a way to get the 'canonical' ordering from all of our diagrams/tests?

 CUDA grad qdata vector: (16 qpts per element)
```
CeedVector length 288
    0.18150449
    0.34027778
    0.34027778
    0.18150449
    0.34027778
    0.63793995
    0.63793995
    0.34027778
    0.34027778
    0.63793995
    0.63793995
    0.34027778
    0.18150449
    0.34027778
    0.34027778
    0.18150449
    0.18150449
    0.34027778
    0.34027778
    0.18150449
    0.34027778
    0.63793995
    0.63793995
    0.34027778
    0.34027778
    0.63793995
    0.63793995
    0.34027778
    0.18150449
    0.34027778
    0.34027778
    0.18150449
...
```
CPU serial qdata vector:
```
CeedVector length 288
    0.18150449
    0.34027778
    0.34027778
    0.18150449
    0.34027778
    0.63793995
    0.63793995
    0.34027778
    0.34027778
    0.63793995
    0.63793995
    0.34027778
    0.18150449
    0.34027778
    0.34027778
    0.18150449
    0.08066866
    0.15123457
    0.15123457
    0.08066866
    0.15123457
    0.28352887
    0.28352887
    0.15123457
    0.15123457
    0.28352887
    0.28352887
    0.15123457
    0.08066866
    0.15123457
    0.15123457
    0.08066866
...
```

**Comment by jeremylt** [comment]
The CUDA backends pass `t204`, which means that the CUDA backends provide the ordering [elem1field1, elem1field2, elem2field1, elem2field2, elem3field1, elem3field2] for the test. But this is not always the ordering followed? OperatorApply, as far as I can tell needs [elem1field1, elem2field1, elem3field1, elem1field2, elem2field2, elem3field3].

**Comment by jeremylt** [comment]
@jedbrown, what do you think about adding an interface intended for cross backend use cases like this that applies ElemRestrictions to some common layout? Something like 'CeedElemRestrictionApplyCanonical/Common/Namingishard'? I think it might be needed for this fallback technique to work right.

**Comment by nbeams** [comment]
`t204` just involves the E-vectors, though, right?  In the first example, I think you are talking about Q-vectors? 

From my time figuring out the CUDA data layouts due to the MAGMA delegation, I've found that for cuda/ref at least, the E-vectors have element as slowest index, but Q-vectors have component as slowest index.  I think following the notation in your comment that would mean:
E-vector:  [elem1field1, elem1field2, elem2field1, elem2field2, ...]
Q-vector: [elem1field1, elem2field1, elem1field2, elem2field2, ...] 
Though since you mentioned "fields" here, are you talking about the total input/output (e.g. Jacobian and weights)?  In that case my comment may be irrelevant.

At any rate, I'm interested in this conversation because of what we've been discussing for the proposed changes to the MAGMA element restrictions.  An interface where we could implement a different version of the element restriction for certain uses (and to pass the t200 tests that I whitelisted for now) could be useful for us.

**Comment by jeremylt** [comment]
I am talking about a multi field input like a Jacobian here. I didn't expect the basis could reorder the data.

Ultimately, for this fallback implementation of building diagonals and element inverses to work consistently, I need a way to get a single element's q vectors, or get information about block size in the qdata.

**Comment by nbeams** [comment]
Hmm, could there be any benefit in having a top-level interface structure in which each backend sets information about its specific E- and Q-vector layouts, with information defining the stride between, e.g., elements in the same component, or the next component for the same element? (Maybe set during backend-specific part of CeedInit?)  If this structure had the right information, any top-level interface function could correctly pull out the desired part(s) of a vector created by any backend, with the same code.  In addition to the AssembleLinear* functions or future features like them, this would allow the t20* tests to be written such that any correct element restriction (correct meaning "not buggy") passes the same tests.

I'm not sure how this would affect performance.  Maybe as long as each backend has the option of re-implementing the fallback functions if they want to...?  So the reference/fallback version of the function may not be optimized like if it "knew" the layout ahead of time, but it would be guaranteed to be correct when used in conjunction with any backend. 

Also if it's preferred to put more of this in the backends, maybe have a suite of "extractor" functions (thinking of how deal.II deals with multi-component finite elements) for both E-vectors and Q-vectors, to be implemented by each backend?  Including the special element restriction you mentioned, but with more functions, too, allowing for the E-vector and Q-vector layouts to be independent (as they currently are for cuda backends).

Just throwing out ideas!

**Comment by jeremylt** [comment]
The goal with the fallback is to provide a basic implementation of these preconditioning tools but to allow backends to implement their own optimized versions. Right now the Blocked and Opt backends override the fallback but the OCCA backends do not. But I've run into this data layout problem with the CUDA backends.

I'm not sure if I prefer the idea of a canonical reordering functionality or some sort of struct full of layout data. I think some sort of canonical restriction would be easier to use.

**Comment by jeremylt** [comment]
@YohannDudouit, I've been looking at this and the CUDA backends more. What I really need is a way to convert the qdata from the CUDA ordering to the CPU ordering and vice versa. If I have this, then I can restore then operator fallback and the CUDA backends will have easy access to the preconditioning based on the operator diagonal and the new techniques we are developing.

**Comment by YohannDudouit** [comment]
I think it's a good idea, and it should also be used in the `CeedElemRestriction` tests, I proposed in the past to have such a function to leave more freedom on the intermediary data layouts. We need to find what would be a reasonable signature for this new interface function, and then I can write it for the different CUDA backends.
