### ISSUE TITLE
Change examples/ceed example names?

### ISSUE THREAD

**Issue by valeriabarra** [CEED/libCEED#441]
This is a minor concern, but in the review process of PR #439 a question arose on whether we wanted to rename the `ceed` examples to something more meaningful than just a numeral.

Some ideas to still preserve the numbering and give them more self-explanatory names:

1. `ex1 -> ex1-volume` (even though it can compute length, area, and volume), and `ex2 -> ex2-area` (to reflect the other area examples in `petsc`)
2. `ex1 -> ex1-volume` and `ex2 -> ex2-surface`

Preferences and /or other ideas are welcome!

**Comment by jeremylt** [comment]
I like `ex1-volume` and `ex2-surface` personally. In ex1 we're using the volumetric terms to find volume/mass and in ex2 we're using the absence of surface integral terms to do surface area.

**Comment by jedbrown** [comment]
Agreed.

**Comment by valeriabarra** [comment]
Ok! I can do a quick dedicated PR for this, as soon as soon as PR #439 gets merged
