### ISSUE TITLE
CUDA + PETSc BPs

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#462]
When running the test suite, I have the following errors on PETSc BPsRaw with the following backends:

`/gpu/cuda/ref`
```
/home/jeth8984/libCEED/backends/cuda/ceed-cuda.c:81 in CeedCompileCuda(): CUDA_ERROR_INVALID_PTX
```

`/gpu/cuda/shared`
```
/home/jeth8984/libCEED/backends/cuda/ceed-cuda.c:110 in CeedRunKernelDimCuda(): CUDA_ERROR_INVALID_VALUE
```

Test parameters
```
# TESTARGS: -ceed {ceed_resource} -test -problem bp2 -degree 5 -qextra 5
```

I intentionally set the test parameters to use almost twice as many qpts as nodes. Dropping to `-qextra 2` fixes the failures. Should we modify the test parameters to something more realistic, try to hunt the issues, or both?

There is also a floating point exception with `petsc-area` and `petsc-bpssphere` for `cuda/shared`.

**Comment by nbeams** [comment]
Do you have more detailed error information about which operation (restriction, basis, QFunction) caused the errors for these backends? 

For `degree = 5` and `qextra = 5`, I believe Q would be (`degree + 1 + qextra`) = 11, which is currently out of the range of the tensor basis kernels in the MAGMA backend (10 is the limit).

However, that doesn't explain the errors in cuda/ref and cuda/shared.

**Comment by jeremylt** [comment]
I think that for `cuda/ref`, `cuda/shared`, and `magma` the `bps-raw` problem is too big. I really have no clue what's up with `area` and `bpssphere` though.

**Comment by jedbrown** [comment]
Too many threads per thread block? `-degree 4 -qextra 2` would be just fine in my book, and perhaps a bit faster to set up. I see `bps.c` just has `-degree 3`.

**Comment by jeremylt** [comment]
The funny number is me trying to fully exercise the AVX backend tensor contractions. I am playing with numbers right now.

**Comment by jeremylt** [comment]
Update:
Now only we only have the `/gpu/cuda/shared` issues with `petsc-area` and `petsc-bpsphere`.

**Comment by valeriabarra** [comment]
Which are the only two examples (so far) that have topological element dimension different from geometrical dimension. I wonder if something funny happens in the data layout then

**Comment by jeremylt** [comment]
That is my suspicion as well. `/cuda/reg` and `/cuda/shared` only differ by their basis action, which narrows it down.
