### ISSUE TITLE
Multigrid Interface - MFEM Ex 26

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#541]
A lot of our prolongation/coarsening code in multigrid.c and elasticity.c can be brought up the library level to make it easier for users to make libCEED operators for multigrid preconditioning.

I would like to get [MFEM example 26](https://github.com/mfem/mfem/blob/master/examples/ex26.cpp) working cleanly with MFEM + libCEED + CUDA. To do so requires

- [x] Easier prolongation/coarsening setup - perhaps `OperatorCreateFromGallery()`?

- [x] `CeedOperatorAssembleLinearDiagonal()` support in CUDA/GPU backends

- [x] `CeedOperatorAssembleLinearBlockDiagonal()` so we support more smoothers

- [ ] In the more general case, it would be nice to add `CeedOperatorAssembleDiagonal()` and `CeedOperatorAssembeBlockDiagonal()` for non-linear CeedOperators.

To show full integration with MFEM will require some work over there as well once I have these interfaces set up.

**Comment by knepley** [comment]
It would be _much_ more useful to assemble defined blocks, rather than the block diagonal. That essentially works for only very simple toy problems.

**Comment by jeremylt** [comment]
Block diagonal is only a relatively small modification from the current diagonal assembly code and its useful in some non-toy problems we are working on, so its the next logical step for our code base. I'm sure it won't be a end point in our support of preconditioners.

**Comment by v-dobrev** [comment]
Just to clarify: example 26 in MFEM works with libCEED and CUDA as it is -- this is one of the sample runs we test: https://github.com/mfem/mfem/blob/261fd7adcd8312fbe05906eb40ca87a1f9c34132/examples/ex26.cpp#L16

However, currently it only uses operator application from libCEED -- the other components are built by MFEM. It should be relatively easy to swap some of those with libCEED implementations when using the libCEED backend in MFEM.

**Comment by jeremylt** [comment]
This work is completed on the libCEED side. MFEM integration is WIP
