### ISSUE TITLE
VecResetArray

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#575]
We should create

1) `CeedVectorResetArray(vec)` to replace use of `CeedVectorSetArray(vec, CEED_MEM_HOST, NULL)`

2) `CeedVectorTakeArray(vec)` to do `CeedVectorSyncArray(vec, memtype)` + `CeedVectorResetArray(vec)`

For 1) this is just a clearer renaming so its obvious what the effect is.

In the case of 2) the sync call would be against the last `memtype` used in `CeedVectorSetArray()` with `CEED_USE_POINTER`.

See discussion in #566

**Comment by jedbrown** [comment]
Can `Reset` be used safely on its own?
```c
VecGetArray(X, &xhost);
CeedVectorSetArray(xceed, CEED_MEM_HOST, xhost);
CeedOperatorApply(..., xceed, ...); // runs on GPU
CeedVectorResetArray(xceed, &xhost); // host values are junk unless there is a sync
```

**Comment by jeremylt** [comment]
I'm thinking about cases internal to a backend where there is no need to sync. See https://github.com/CEED/libCEED/blob/b21f0643081e4808cdebb3789595c6dc6dbda6b0/backends/ref/ceed-ref-operator.c#L615

It neither is useful nor harmful to have a sync there.

**Comment by jedbrown** [comment]
The sync would be a no-op, right? So long as we can make the no-op fast (I don't see why it wouldn't be), I'd rather the interface do it.

**Comment by jeremylt** [comment]
Works for me.

I noticed that you have `CeedVectorResetArray(vec, array) `. Do we want to do that? There are cases where the parent code wants to retain the pointer, so we wouldn't want to null the pointer. And that wouldn't be the easiest way to keep track of which pointer to sync - why not just state in the interface what memory to sync or track that internally?

**Comment by jedbrown** [comment]
Perhaps `CeedVectorTakeArray(vec, &array)` that *sets* `array` and allows `CeedVectorTakeArray(vec, NULL)` if the caller already has it or doesn't care?

**Comment by jeremylt** [comment]
Ah. If its going to *set* the array pointer, then I'd say that we should explicitly include the memtype so that its clear what the user is getting.

**Comment by jedbrown** [comment]
Yeah, I agree.
