### ISSUE TITLE
Diagnostic not loaded: Could not open 'Fields0.h5'

### ISSUE THREAD

**Issue by Sanjeev273** [CEED/libCEED#630]
I have data file from smilei simulation: Fields0.h5

I am using the following python script to acess the data:  

import happi
S = happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM")
Diag = S.Field(0, "Ex")
result = Diag.getData()
ne = S.Field(0, field = "-Rho_electron", label= "ne")
np = S.Field( 0, field= "Rho_proton", label = "np")
happi.multiPlot(ne, np, saveAs= " ./dens.png" )

I got the msg in output file: Diagnostic not loaded: Could not open 'Fields0.h5'. Can anyone help me. is there anything wrong in python script or is it could be a problem in data file. I am not getting any error msg.

**Comment by jeremylt** [comment]
I don't think this has anything to do with libCEED. I'm not seeing any libCEED code in that script. I'm not familiar with smilei.

**Comment by Sanjeev273** [comment]
> 
> 
> I don't think this has anything to do with libCEED. I'm not seeing any libCEED code in that script. I'm not familiar with smilei.

it is python script. there is nothing with smilei. here only I am trying to analysis data file using python.

**Comment by jeremylt** [comment]
I'd look at the happi documentation:
https://github.com/pcdshub/happi
https://pcdshub.github.io/happi/

I closed this issue because it is unrelated to libCEED.
