### ISSUE TITLE
Add debug-mode checks that every GetArray has a matching RestoreArray

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#64]
`CeedVectorGetArray` and `CeedVectorGetArrayRead` are supposed to always be paired with `CeedVectorRestoreArray` and `CeedVectorRestoreArrayRead` respectively, but sometimes users and even backend developers such as myself accidentally forget. In debug mode, the interface should track access so that it can warn in case of non-exclusive write access or if `CeedVectorDestroy` is called while some caller has access. When available, this functionality could print a stack trace using [backtrace](https://www.gnu.org/software/libc/manual/html_node/Backtraces.html) from glibc or [libbacktrace](https://github.com/ianlancetaylor/libbacktrace).

**Comment by jeremylt** [comment]
PR #120
