### ISSUE TITLE
Symmetric Schur decomposition fails for diagonal matrix

### ISSUE THREAD

**Issue by pazner** [CEED/libCEED#645]
The following simple example fails with error `Symmetric QR failed to converge`:
```c
#include <ceed.h>

int main() {
  Ceed ceed;
  CeedInit("/cpu/self/ref", &ceed);
  double A[9] = {
    1, 0, 0,
    0, 1, 0,
    0, 0, 1};
  CeedScalar lambda[3] = {0.0};
  CeedSymmetricSchurDecomposition(ceed, A, lambda, 3);
  return 0;
}
```
In particular, this causes `CeedOperatorCreateFDMElementInverse` to fail when the quadrature points and nodal points are the same, so the mass matrix is diagonal.

In general, `t540-operator.c` seems pretty fragile — changing `P` to values other than 4 does not work for me.

**Comment by jeremylt** [comment]
That is a pretty experimental feature.

 Can you provide some more context? A constant coefficient mass matrix with collocated quadrature is not the intended use of this function since that is trivial to create by hand.

**Comment by pazner** [comment]
> Can you provide some more context? A constant coefficient mass matrix with collocated quadrature is not the intended use of this function since that is trivial to invert by hand.

Of course, but it doesn't make sense for this feature to work for the nontrivial cases, and then to break for the trivial case.

> That said, it is strange that the symmetric QR did not converge.
> 
> Whe you say that p=4 only works, are you changing both p and q?

Yes, I haven't been able to find a `Q` that works, given, for example, `P=5`. This could be because of some other issue in the test that is distinct from my original issue, but it seemed worth mentioning.

**Comment by jeremylt** [comment]
Though, I would still need to factor the collocated mass matrix if the user has any collocated problem. I don't see an obvious reason why it's not working. I might have mangled the algorithm from the matrix methods book I have.
