### ISSUE TITLE
MAGMA CI

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#654]
This issues lets us continue our discussion investigating the trouble we've had building hipMAGMA for ROCm 3.9

**Comment by nbeams** [comment]
I don't have permission to edit the `make.inc` in noether's `/projects/hipMAGMA`, but I was able to get a working MAGMA + libCEED combination on an ICL machine with ROCm 3.9.  

Here's what I changed: 

1. in `make.inc` for MAGMA:

  -  Change `FOPENMP` to `-fopenmp`
  -  Add new flag variable, `DEVOPENMP   =  -Xopenmp-target=amdgcn-amd-amdhsa`
  - Change `DEVCCFLAGS += $(FPIC) $(FOPENMP) -std=c++11` to `DEVCCFLAGS += $(FPIC) $(DEVOPENMP) -std=c++11`

2. in libCEED's Makefile, change `HIPCCFLAGS` definition to 
  `HIPCCFLAGS ?= -O -g $(MARCHFLAG) $(OPT.$(CC_VENDOR)) -fPIC`.  (What this actually does is just remove the `$(OMP_SIMD_FLAG)` from `HIPCCFLAGS`. )

This combination worked with the following compiler options:
MAGMA build with `CC=gcc`, `CXX=g++` (GCC 9.2)
libCEED build with `CC=gcc`, `CXX=g++` (GCC 9.2) or `CC=/opt/rocm/llvm/bin/clang`, `CXX=/opt/rocm/llvm/bin/clang++` (the LLVM-12.0 shipped with ROCm 3.9)

I'm not yet sure whether this is the *optimal* flag combination, or if it will work for all compilers + CPU options, but it's a start...
