### ISSUE TITLE
Julia formatting stability for CI

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#690]
JuliaFormatter.jl has made a couple releases recently that change our code rendering. I applied changes in v0.12.0 (97769a3d2c45e9067c16da7ef18281dfae6857b7) on Friday, but there are more changes now and the diff below seems odd. I believe we can pin the versions in `.style/Project.toml` so we stop having surprising CI failures, but what should we do with the case below?

```diff
diff --git i/julia/LibCEED.jl/src/Cuda.jl w/julia/LibCEED.jl/src/Cuda.jl
index 372871ad..4a13c1d7 100644
--- i/julia/LibCEED.jl/src/Cuda.jl
+++ w/julia/LibCEED.jl/src/Cuda.jl
@@ -86,8 +86,8 @@ function generate_kernel(qf_name, kf, dims_in, dims_out)
     end

     def_outs = [
-        :($(f_outs[i]) = LibCEED.MArray{Tuple{$(dims_out[i]...)},Float64}(undef))
-        for i = 1:noutputs
+        :($(f_outs[i]) = LibCEED.MArray{Tuple{$(dims_out[i]...)},Float64}(undef)) for
+        i = 1:noutputs
     ]

     device_ptr_type = Core.LLVMPtr{CeedScalar,LibCEED.AS.Global}
```

**Comment by pazner** [comment]
It's a bit unfortunate that a change in the 0.0.x version number of JuliaFormatter results in diffs — I wasn't expecting that.

What do you think about just pinning to v0.12.0?
