### ISSUE TITLE
LibCEED.jl data movement

### ISSUE THREAD

**Issue by valeriabarra** [CEED/libCEED#704]
Hello! 

I would like to explore the possibilities to start using/trying out `LibCEED.jl` for operator evaluations in CliMA (even if this is a remote option for now, it could be good to keep it in mind as a reference in terms of accuracy and performance). 

Before even thinking of compatibility of the interfaces and storage categories, a question arose on libCEED's Julia interface to be able to get around excessive data movement easily. 

Is this a known limitation of the current interface? Are there copies? 

Thanks. 

cc: @pazner @jkozdon @simonbyrne

**Comment by jeremylt** [comment]
@pazner  would be the expert, but if I understand the code (and my memory) correctly, I believe that the Julia interface supports zero-copy transfer of CUDA array pointers back and forth.

https://github.com/CEED/libCEED/blob/3d576824e8d990e1f48c6609089904bee9170514/julia/LibCEED.jl/src/Cuda.jl#L46
https://github.com/CEED/libCEED/blob/3d576824e8d990e1f48c6609089904bee9170514/julia/LibCEED.jl/src/CeedVector.jl#L178

**Comment by pazner** [comment]
Yes, it should be generally possible to avoid copies with the Julia interface. It is possible that there are some deficiencies in the current implementation, but nothing that can't be fixed.

One big limitation is that the Julia interface is not compatible with the cuda/gen backend.

**Comment by jeremylt** [comment]
Yeah, I think we chatted with @YohannDudouit about the possibility of modifying cuda/gen to optionally use a CUFunction for the QFunction, but I don't recall what we decided about that.

**Comment by jedbrown** [comment]
A question for the CLiMA team: do you need bitwise determinism? The fastest implementations on recent-gen CUDA devices use atomics for accumulation with continuous Galerkin. Depending on the element degree, it can be a significant perf hit to require determinism, but lots of climate modelers insist on it.

As for fusing Julia QFunctions into libCEED GPU kernels, this is something we'd like to support and I'd expect we could find a strategy between CUDA.jl and our backend code. If it ends up hinging on some missing nvrtc/hiprtc capability, I think we could get vendor support -- it's in their strategic interest for this to be possible. The good news is that you can carry on with other backends in the meantime.

**Comment by simonbyrne** [comment]
> A question for the CLiMA team: do you need bitwise determinism? The fastest implementations on recent-gen CUDA devices use atomics for accumulation with continuous Galerkin. Depending on the element degree, it can be a significant perf hit to require determinism, but lots of climate modelers insist on it.

No, that isn't something we're insisting on at the moment.

**Comment by jeremylt** [comment]
Closing - please reopen if this requires further action
