### ISSUE TITLE
GPU resource names and device IDs

### ISSUE THREAD

**Issue by nbeams** [CEED/libCEED#709]
Recently, in fdf826bb480f6f0c657574035d43bde2679baed8, the code used by the CUDA and HIP backends to determine the device ID was changed slightly, to avoid resetting to device 0 if another library had already set it to a different value.  However, it seems this has had the (unintended?) effect of removing the "pick the best HIP/CUDA backend" resource option of `/gpu/cuda` or `/gpu/hip` (which would pick the cuda-gen or hip-gen backends currently).  This affects MFEM, as it uses only `/gpu/hip` for its default `ceed-hip` backend (done originally rather than hard-code `/gpu/hip/ref`, the first-available HIP backend).  

The reason `/gpu/cuda` and `/gpu/hip` no longer work is because  in `Ceed[Cuda/Hip]Init`, `deviceID` is set to -1, then used for `*GetDeviceProperties`, which will throw an error for the invalid ID.  An easy fix for this is to set `deviceID = currentDeviceID` as an `else` condition if we don't end up calling `hipSetDevice` to change the `deviceID`.  However, after looking some more at this, I realized I wasn't sure what the expected behavior was really intended to be. 

From looking at the code in `CeedHipInit`, I assumed that the way a user would specify a device ID would be to add it at the end, e.g., `/gpu/hip/shared/1`.  However, because the `nrc` is set to 8 (or 9 for cuda) to allow matching for the "pick the best case" scenario, it seems that the line
```
int deviceID = (slash && rlen > nrc + 1) ? atoi(&resource[nrc + 1]) : -1;
```

would result in `atoi(s)` in this case, which returns 0 -- the number at the end of the string is ignored.   (And this is also why `/gpu/hip/ref`, `/gpu/hip/shared`, and `/gpu/hip/gen` do not encounter the same error as `/gpu/hip` - because they all have the case where `slash && rlen > nrc + 1` is true, but thanks to the short `nrc` value, the `atoi` call is on a non-numeric character, which returns 0.) 

Also, I realized we don't have this sort of check/expectation that the user can set the device ID from the resource string in the MAGMA backend at all -- we only get the current device.  Thus, I want to make sure I understand the way this capability is supposed to work.

**Comment by jedbrown** [comment]
I think you have the intent right (though this should be documented and tested if it's intended behavior), but I'm concerned that this approach will become ambigous and perhaps we should allow key-value pairs in the resource string. So we'd have something like `/gpu/hip/gen:device=1`. Good/bad?

**Comment by nbeams** [comment]
I like that idea.  I think it's clear and allows for an easy way to search the resource string for device specification (while still allowing `/gpu/cuda` and `/gpu/hip` to work properly if we want).
