### ISSUE TITLE
Installation on SUMMIT

### ISSUE THREAD

**Issue by ArashMehraban** [CEED/libCEED#711]
I am reporting installation and compilation issues that I have encountered when I install PETSc and libCEED on CU SUMMIT, hereby refereed to as summit:

This script was the latest I used on summit and it fails running the solids code after all installations are "successfully" done. (This was last tested months ago):
  
`#!/bin/bash

#To build libsxmm, libCEED and PETSC, we used the following modules
ml purge
ml valgrind/3.11.0
ml autotools/2.69

SOFTWARE_DIR=software

#MAKE A SOFTWARE DIRECTORY IF ONE DOES NOT EXIST
mkdir -p /projects/$USER/$SOFTWARE_DIR

#COMPILE PETSC
cd /projects/$USER/$SOFTWARE_DIR
git clone https://gitlab.com/petsc/petsc.git
cd petsc
mkdir local
#git checkout knepley/feature-fe-lagrange-gll
./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --with-valgrind-dir=$CURC_VALGRIND_ROOT --download-make --download-cmake --download-mpich --download-fblaslapack --download-parmetis --download-metis --download-zlib --download-hdf5 --download-netcdf --download-pnetcdf --download-exodusii COPTFLAGS="-O3 -march=native" FOPTFLAGS="-O3 -march=native" CXXOPTFLAGS="-O3 -march=native" --with-debugging=0 --with-shared-libraries=1 --prefix=$PWD/local
make PETSC_DIR=/projects/$USER/$SOFTWARE_DIR/petsc PETSC_ARCH=arch-linux2-c-opt all
make PETSC_DIR=/projects/$USER/$SOFTWARE_DIR/petsc PETSC_ARCH=arch-linux2-c-opt install

#COMPILE LIBXSMM
cd /projects/$USER/$SOFTWARE_DIR
git clone https://github.com/hfp/libxsmm.git
cd libxsmm/
make

#COMPILE LIBCEED
cd /projects/$USER/$SOFTWARE_DIR
git clone https://github.com/CEED/libCEED.git
cd libCEED/
make OPT="-O3 -march=native" BLAS_LIB=/projects/arme5062/software/petsc/local/lib/libfblas.a

#COMPILE CeedPetscSolid
cd /projects/$USER/$SOFTWARE_DIR
#Option 1: get source code:
#https://github.com/ArashMehraban/CeedPetscSolid
#Option 2: Copy existing directory and recompile
cp -r /projects/$USER/CeedPetscSolid .
cd CeedPetscSolid
make clean
make`

**Comment by jeremylt** [comment]
Two things

1) We *cannot* build PETSc if we want reasonable performance on CU Summit. We have to use their PETSc + their MPI.

2) This doesn't list any error messages. I'll figure out what's happening sometime today hopefully and post error messages as I get them.

**Comment by ArashMehraban** [comment]
Sounds good. Item number 1 raises the question for me that how about if the PETSc and MPI installations they have is out of date for us?

**Comment by ArashMehraban** [comment]
So while you are trying on your end, I am gonna see if I can provide you with errors I get if I clone, compile and run the latest version of solids code on summit

**Comment by jeremylt** [comment]
That doesn't have anything to do with PETSc. The correct BLAS module needs to be loaded for LIBXSMM to be happy.

**Comment by jeremylt** [comment]
Right, because we need to use one of their built in BLAS [modules](https://curc.readthedocs.io/en/latest/compute/modules.html)

**Comment by jedbrown** [comment]
* We have to use their MPI, but we can definitely build our own PETSc.
* PETSc 'main' (the default branch) is fine. That old branch you used was merged and no longer exists.
* Either use system BLAS (probably MKL) or `--download-f2cblaslapack --download-blis`. This builds faster and BLIS is faster than the alternatives. This is important for libxsmm.

**Comment by jeremylt** [comment]
The funny thing is, our LIBXSMM backends don't actually use BLAS/BLIS on this problem.

**Comment by ArashMehraban** [comment]
I just did an `ml avail` and they do not have BLAS/BLIS by itself. I am gonna reinstall PETSc with the `--download-f2cblaslapack` and `--download-blis` to see where it goes.

![ml](https://user-images.githubusercontent.com/10523693/110676613-020f6c80-8189-11eb-977e-fd080f65ace5.png)


Do you have any suggestions on the rest of the config below (coming from Andy)? I do not like the `--prefix` stuff or that `local`. I am not sure why Andy had them.

```./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --with-valgrind-dir=$CURC_VALGRIND_ROOT --download-make --download-cmake --download-mpich --download-fblaslapack --download-parmetis --download-metis --download-zlib --download-hdf5 --download-netcdf --download-pnetcdf --download-exodusii COPTFLAGS="-O3 -march=native" FOPTFLAGS="-O3 -march=native" CXXOPTFLAGS="-O3 -march=native" --with-debugging=0 --with-shared-libraries=1 --prefix=$PWD/local```

**Comment by ArashMehraban** [comment]
To my surprise he has `--download-mpich` and `--download-fblaslapack`

**Comment by jeremylt** [comment]
I was going to get things working without rebuilding PETSc first and then rebuild PETSc if needed. One of those modules has BLAS bundled in it but I don't recall which. I'm having some login issue right now, so I haven't been able to play around.

**Comment by ArashMehraban** [comment]
Sure, Thanks. You may load Jed's installation there too. I would load it like this:
-bash-4.2$ export SLURM_EXPORT_ENV=ALL
-bash-4.2$ 
-bash-4.2$ export PETSC_DIR=/projects/jeka2967/petsc PETSC_ARCH=ompi-gcc8-O3
(That is what I used before)

Then we can try building PETSc from scratch again. In essence, I am hoping we can find a list of modules to load and `./confg`  list for PETSc

**Comment by jeremylt** [comment]
Just loading the minimum modules for PETSc and LIBXSMM (intel, impi, and mkl), we do have compatibility issues with older PETSc

<details>

```
[jeth8984@shas0136 libCEED]$ make prove search=sol
make: 'lib' with optional backends: /cpu/self/xsmm/serial /cpu/self/xsmm/blocked /cpu/self/tmpl /cpu/self/tmpl/sub
make -C examples/solids CEED_DIR=`pwd` \
  PETSC_DIR="/curc/sw/petsc/3.8.0/impi/17.3/intel/17.4" OPT="-O -g   -qopenmp-simd" elasticity
make[1]: Entering directory `/projects/jeth8984/libCEED/examples/solids'
          CC build/elasticity.o
In file included from /projects/jeth8984/libCEED/examples/solids/elasticity.c(43):
/projects/jeth8984/libCEED/examples/solids/elasticity.h(206): error: identifier "PetscMemType" is undefined
  static inline CeedMemType MemTypeP2C(PetscMemType mtype) {
                                       ^

In file included from /projects/jeth8984/libCEED/examples/solids/elasticity.c(43):
/projects/jeth8984/libCEED/examples/solids/elasticity.h(207): warning #266: function "PetscMemTypeDevice" declared implicitly
    return PetscMemTypeDevice(mtype) ? CEED_MEM_DEVICE : CEED_MEM_HOST;
           ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(144): error: identifier "VECHIP" is undefined
      else if (strstr(resolved, "/gpu/hip")) vectype = VECHIP;
                                                       ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(162): warning #266: function "DMGetLocalSection" declared implicitly
      ierr = DMGetLocalSection(levelDMs[level], &section); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(164): warning #266: function "PetscSectionSetComponentName" declared implicitly
      ierr = PetscSectionSetComponentName(section, 0, 0, "DisplacementX");
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(185): warning #266: function "DMGetLocalSection" declared implicitly
      ierr = DMGetLocalSection(dmDiagnostic, &section); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(187): warning #266: function "PetscSectionSetComponentName" declared implicitly
      ierr = PetscSectionSetComponentName(section, 0, 0, "DisplacementX");
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(250): error: identifier "PetscMemType" is undefined
    PetscMemType fmemtype;
    ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(252): warning #266: function "VecGetArrayAndMemType" declared implicitly
      ierr = VecGetArrayAndMemType(Floc, &f, &fmemtype); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(260): error: identifier "PetscMemType" is undefined
    PetscMemType nmemtype;
    ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(264): warning #266: function "VecGetArrayAndMemType" declared implicitly
      ierr = VecGetArrayAndMemType(NBCsloc, &n, &nmemtype); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(288): warning #266: function "DMLocalToGlobal" declared implicitly
      ierr = DMLocalToGlobal(levelDMs[level+1], Uloc[level+1], ADD_VALUES,
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(290): warning #266: function "DMGlobalToLocal" declared implicitly
      ierr = DMGlobalToLocal(levelDMs[level+1], Ug[level+1], INSERT_VALUES,
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(295): error: identifier "PetscMemType" is undefined
      PetscMemType mmemtype;
      ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(296): warning #266: function "VecGetArrayReadAndMemType" declared implicitly
      ierr = VecGetArrayReadAndMemType(Uloc[level+1], &m, &mmemtype); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(309): warning #266: function "VecRestoreArrayReadAndMemType" declared implicitly
      ierr = VecRestoreArrayReadAndMemType(Uloc[level+1], &m); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(324): warning #266: function "VecRestoreArrayAndMemType" declared implicitly
      ierr = VecRestoreArrayAndMemType(Floc, &f); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(325): warning #266: function "DMLocalToGlobal" declared implicitly
      ierr = DMLocalToGlobal(levelDMs[fineLevel], Floc, ADD_VALUES, F);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(333): warning #266: function "VecRestoreArrayAndMemType" declared implicitly
      ierr = VecRestoreArrayAndMemType(NBCsloc, &n); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(334): warning #266: function "DMLocalToGlobal" declared implicitly
      ierr = DMLocalToGlobal(levelDMs[fineLevel], NBCsloc, ADD_VALUES, NBCs);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(435): warning #266: function "MatShellSetVecType" declared implicitly
      ierr = MatShellSetVecType(jacobMat[level], vectype); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(478): warning #266: function "MatShellSetVecType" declared implicitly
      ierr = MatShellSetVecType(prolongRestrMat[level], vectype); CHKERRQ(ierr);
             ^

/projects/jeth8984/libCEED/examples/solids/elasticity.c(813): warning #266: function "DMLocalToGlobal" declared implicitly
      ierr = DMLocalToGlobal(resCtx->dm, resCtx->Yloc, INSERT_VALUES, trueVec);
             ^

compilation aborted for /projects/jeth8984/libCEED/examples/solids/elasticity.c (code 2)
make[1]: *** [build/elasticity.o] Error 2
rm build/.DIR
make[1]: Leaving directory `/projects/jeth8984/libCEED/examples/solids'
make: *** [build/solids-elasticity] Error 2
```

</details>

**Comment by ArashMehraban** [comment]
I remember having compile time errors like this with the older PETSc that I had also.

**Comment by jeremylt** [comment]
Modules/environment:
```
ml gcc/8.2.0
ml openmpi
export PETSC_DIR=/projects/jeth8984/petsc PETSC_ARCH=ompi-gcc8-O3
```
or for Skylake (currently building)
```
export PETSC_DIR=/projects/jeth8984/petsc PETSC_ARCH=ompi-gcc8-O3-skylake
```
LIBXSMM:
```
make -j8
```
libCEED:
```
export MKL=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64
export MKL_ROOT=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl
make OPT="-O3 -march=native" prove search=solids -j8
```

**Comment by jeremylt** [comment]
For reference, I shamelessly stole the config options from Jed, down to the arch naming
```
--download-exodusii --download-hdf5 --download-hypre --download-metis --download-ml  --download-netcdf --download-parmetis --download-pnetcdf --download-zlib --with-blaslapack-dir=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64 --with-debugging=0 --with-fortran-bindings=0 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-Ofast -march=haswell -g" PETSC_ARCH=ompi-gcc8 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-O3 -ffp-contract=fast -march=haswell" PETSC_ARCH=ompi-gcc8-O3
```

**Comment by jeremylt** [comment]
Just compiled straight off of PETSc master.

**Comment by ArashMehraban** [comment]
Cool. I build my own too. I want to make sure this is reproducible on summit.

**Comment by ArashMehraban** [comment]
Once I build and run everything, I create a instructions set here to build this on summit. Next I will move to install stuff on TACC. It would be cool to see how the code runs on, I don’t know, 50K cores :)

**Comment by jeremylt** [comment]
The instruction set should be pretty simple:
Load the modules
```
ml gcc/8.2.0
ml openmpi
ml cmake
ml autotools
```
Build PETSc with the options
```
--download-exodusii --download-hdf5 --download-hypre --download-metis --download-ml  --download-netcdf --download-parmetis --download-pnetcdf --download-zlib --with-blaslapack-dir=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64 --with-debugging=0 --with-fortran-bindings=0 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-Ofast -march=haswell -g" PETSC_ARCH=ompi-gcc8 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-O3 -ffp-contract=fast -march=haswell" PETSC_ARCH=ompi-gcc8-O3
```
Build LIBXSMM with
```
make -j8
```
Build libCEED with
```
export MKL=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64
export MKL_ROOT=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl
make OPT="-O3 -march=native" prove search=solids -j8
```

**Comment by ArashMehraban** [comment]
Did you run the solid code by any chance?

**Comment by jedbrown** [comment]
There's a newer MKL. And you can edit your comment above to not list `COPTFLAGS` twice (last one is used).

**Comment by jeremylt** [comment]
> Did you run the solid code by any chance?

Yep 
```
make OPT="-O3 -march=native" prove search=solids -j8
```
the test suite passed fine.

> And you can edit your comment above to not list `COPTFLAGS` twice (last one is used).

Woops, bad copy-paste of your config file

**Comment by ArashMehraban** [comment]
I update as I go through:

It is configuring PETSc. Should I care about these Warnings:

![petsc-warning](https://user-images.githubusercontent.com/10523693/110704528-ee283280-81a9-11eb-8940-ee60a754f962.png)

**Comment by ArashMehraban** [comment]
checking libraries fail: Here are pictures of two errors:
Here is the instructions so far:

03/10/2021
Instrcutions to Install PETSc, libCEED, LIBXSSM on CU SUMMIT:
Once logged in to CU SUMMIT, switch to a compiple node:

0) `ssh scompile`

1) cd /projects/{your username such as arme5062}

2) Clone PETSc from https://www.mcs.anl.gov/petsc/download/index.html

`git clone -b release https://gitlab.com/petsc/petsc.git petsc`

3) Load the following modules:
`ml gcc/8.2.0`
`ml openmpi`
`ml cmake`
`ml autotools`

4) Configure PETSc with the following options in the `petsc` directory:
```./configure --download-exodusii --download-hdf5 --download-hypre --download-metis --download-ml  --download-netcdf --download-parmetis --download-pnetcdf --download-zlib --with-blaslapack-dir=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64 --with-debugging=0 --with-fortran-bindings=0 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-Ofast -march=haswell -g" PETSC_ARCH=ompi-gcc8 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-O3 -ffp-contract=fast -march=haswell" PETSC_ARCH=ompi-gcc8-O3```

4) Follow PETSc's instructions
make PETSC_DIR=/projects/arme5062/software/petsc PETSC_ARCH=ompi-gcc8-O3 all


![check1](https://user-images.githubusercontent.com/10523693/110707003-870c7d00-81ad-11eb-814b-34a6693b6975.png)
![check2](https://user-images.githubusercontent.com/10523693/110707016-8aa00400-81ad-11eb-91fc-8603f42b3e0f.png)

**Comment by jedbrown** [comment]
Looks like you're running on a compile node.

**Comment by ArashMehraban** [comment]
Shouldn't this:
`make PETSC_DIR=/projects/arme5062/software/petsc PETSC_ARCH=ompi-gcc8-O3 all`
be done on a compile node? I did switch to a compile node to configure and install petsc ( `ssh scompile`)

The continuation of installation from this command on the compile node
`make PETSC_DIR=/projects/arme5062/software/petsc PETSC_ARCH=ompi-gcc8-O3 all` 
instructs me to do:
`make PETSC_DIR=/projects/arme5062/software/petsc PETSC_ARCH=ompi-gcc8-O3 check`
where I get those errors

**Comment by jeremylt** [comment]
Right. That check won't work right on a compile node. You'd have to get an interactive session or run a SLURM job.

**Comment by ArashMehraban** [comment]
I see. At this point, I consider it installed. Now I move to installing the rest.

**Comment by ArashMehraban** [comment]
LBXSMM seemed to have built correctly. 

libCEED had an issue the way instructed:

![solids-ibceed](https://user-images.githubusercontent.com/10523693/110710044-0a2fd200-81b2-11eb-9246-e978431832e4.png)

**Comment by ArashMehraban** [comment]
LIBXSMM seemed to have installed properly

**Comment by jeremylt** [comment]
you can also test it with `make test`. Not sure what's wrong with `make prove` in your env

**Comment by ArashMehraban** [comment]
This particular command throws this error:
![libCEED-error](https://user-images.githubusercontent.com/10523693/110710477-c8535b80-81b2-11eb-9aba-dc39bee9ab7d.png)

**Comment by ArashMehraban** [comment]
Should I just do 
`make OPT="-O3 -march=native" `

**Comment by jeremylt** [comment]
did you set the PETSC_DIR and PETSC_ARCH?

**Comment by ArashMehraban** [comment]
Oh Shoot. I am used to `make`ing libCEED separately and then setting PETSC_DIR and PETSC_ARCH for running.

**Comment by ArashMehraban** [comment]
I set  PETSC_DIR and PETSC_ARCH and ran:
`make OPT="-O3 -march=native" prove search=solids -j8`

I have this error: I did not set any env. var. for libxsmm. It folder is next to libCEED. However, I did:

`export MKL=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64`
`export MKL_ROOT=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl`

![libceed](https://user-images.githubusercontent.com/10523693/110711151-e4a3c800-81b3-11eb-8bd6-388006a47a91.png)

**Comment by jeremylt** [comment]
Typo on my part `MKL_ROOT` -> `MKLROOT`

**Comment by jeremylt** [comment]
I found this by looking at what paths we need to help the linker in the Makefile

**Comment by ArashMehraban** [comment]
Sorry my internet went down. I fixed the typo and we have a new set of errors where the compiler does not recognize some functions now:
![libceed-compile1](https://user-images.githubusercontent.com/10523693/110815464-51b06f80-823f-11eb-9456-630329b76ee5.png)
![libceed-compile2](https://user-images.githubusercontent.com/10523693/110815474-5412c980-823f-11eb-9784-80dc28099b13.png)
![libceed-compile3](https://user-images.githubusercontent.com/10523693/110815480-56752380-823f-11eb-95e4-5e00c1ecbf03.png)

**Comment by jeremylt** [comment]
You're not using a clone of the PETSc GitLab repo main branch?

**Comment by ArashMehraban** [comment]
I cloned it like this:

git clone -b release https://gitlab.com/petsc/petsc.git petsc

off this page: https://www.mcs.anl.gov/petsc/download/index.html

**Comment by jeremylt** [comment]
Ok, that means you are using the release branch. You want to switch to the man branch.

**Comment by ArashMehraban** [comment]
OK. I reconfigure then. I'll update

**Comment by ArashMehraban** [comment]
I rather ask this than re-configuring and then asking. when I do a `git branch -r`, I see a big list of branches. So is this the one: 
`origin/main`
`git checkout origin/main`

**Comment by jeremylt** [comment]
Yeah, `get checkout main` will set you up with the main branch as you had just closed normally with `git clone https://GitLab.com/petsc/petsc.git`

**Comment by ArashMehraban** [comment]
Switching to main and re-configuring appeared to have fixed it. I am gonna run with an unstructured mesh tube from Cubit to test it with exodus-ii files too:

![libceed-installed](https://user-images.githubusercontent.com/10523693/110819875-76a6e180-8243-11eb-8850-f089460e8000.png)

**Comment by ArashMehraban** [comment]
03/10/2021
Instrcutions to Install PETSc, libCEED and LIBXSMM on CU SUMMIT:
(This is a specific example with certain PETSC_ARCH name)

Once logged into CU SUMMIT, switch to a compile node:

**PETSc Installation:**

0) `ssh scompile`

1) `cd /projects/{your username such as arme5062}`

1) Clone PETSc from https://www.mcs.anl.gov/petsc/download/index.html

`git clone -b release https://gitlab.com/petsc/petsc.git petsc`

Then switch to the `main` branch from the `release` branch:

`git checkout main` 

2) Load the following modules:
`ml gcc/8.2.0`
`ml openmpi`
`ml cmake`
`ml autotools`

3) Configure PETSc with the following options:
`./configure --download-exodusii --download-hdf5 --download-hypre --download-metis --download-ml  --download-netcdf --download-parmetis --download-pnetcdf --download-zlib --with-blaslapack-dir=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64 --with-debugging=0 --with-fortran-bindings=0 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-Ofast -march=haswell -g" PETSC_ARCH=ompi-gcc8 --with-mpi-dir=/curc/sw/openmpi_ucx/4.0.2/gcc/8.2.0 COPTFLAGS="-O3 -ffp-contract=fast -march=haswell" PETSC_ARCH=ompi-gcc8-O3`

4) Follow PETSc's instructions
`make PETSC_DIR=/projects/arme5062/software/petsc PETSC_ARCH=ompi-gcc8-O3 all`

5) PETSc will instruct you to do this next: (**Ignore it on a compile node**)
`make PETSC_DIR=/projects/arme5062/software/petsc PETSC_ARCH=ompi-gcc8-O3 check`


**LIBXSMM Installation:**

Still on a compile node:

0) Clone LIBXSMM from https://github.com/hfp/libxsmm

`git clone https://github.com/hfp/libxsmm`

1) make LIBXSMM by switching to its folder and:

`make -j8`  


**libCEED Installation:**

Still on a compile node:

0) Clone libCEED form: git clone https://github.com/CEED/libCEED

1) export the following:

`export MKL=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl/lib/intel64`
`export MKLROOT=/curc/sw/intel/parallel_studio_xe_2018_update3_cluster_edition/mkl`

2) Switch to the libCEED directory and:
`make OPT="-O3 -march=native" prove search=solids -j8`

You should see "All tests successful" message.

-------------
**Prepare to run**:

In the subdirectory: `libCEED/examples/solids/`

`make OPT="-O3 -march=native"`

Then, load these modules:

`export SLURM_EXPORT_ENV=ALL`
`module add gcc/8.2.0 openmpi cmake autotools valgrind`

Also make sure to set PETSC_DIR and PETSC_ARCH and CEED_DIR

To set `PETSC_DIR`: 

switch to the `petsc` directory:

`export PETSC_DIR=$PWD`

`export PETSC_ARCH=YOUR_ARCH_NAME`. In this example: `export PETSC_ARCH=ompi-gcc8-O3`

 switch to the `libCEED` directory:

`export CEED_DIR=$PWD`
