### ISSUE TITLE
Why this happens on Noether?

### ISSUE THREAD

**Issue by ArashMehraban** [CEED/libCEED#713]
I am wondering why this happens on Noether?This is a fresh clone. We did new commits under Rezgar to make things work but under my account I cannot even compile solids  (This is not the first time) :

![noether-ssue](https://user-images.githubusercontent.com/10523693/111054239-fbe6ed80-841f-11eb-880e-f09dbb90b45a.png)

**Comment by jeremylt** [comment]
Did you run make in the root libCEED directory?

**Comment by ArashMehraban** [comment]
I worded it poorly. I forgot to re-make after from clone for this case!! However, this has happened after I  `git pull`. Do I need to make the entire libCEED after a `git pull` and then, `make` solids again?

**Comment by jeremylt** [comment]
Any time you make a fresh clone, you need to build libCEED so that you can use the library. I also rebuild when I change branches. A pull that only changes example code shouldn't require a rebuild once the library has been built once though.

**Comment by ArashMehraban** [comment]
"_A pull that only changes example code shouldn't require a rebuild once the library has been built once though._"
I am having an issue with this. Example code was changed only but in order to build the solids code, I had to rebuild libCEED gain too. In essence, I could not `make` the solids code until I rebuilt libCEED again!

**Comment by jeremylt** [comment]
Can you provide an exact series of steps that reproduce this behavior? I don't think I've seen it personally.

**Comment by ArashMehraban** [comment]
We are making four versions of the qfunctions for hyperelasticity:

1) Our original hyperFS
2) Original HyperFS with Cinv stored
3) Using tau and b tensors
4) Using tau and b tensors with F_inv storage in addition to gradu.
We are doing this under Rezgars' machine. Once he commits them. I do a  `git pull` and try to make under my branch. That should reproduce the error. (He watched me having this issue. That is why we switched to his machine.) I will provide steps once we get them all today.

**Comment by ArashMehraban** [comment]
I found out what my problem is. I should have used `git pull origin Add_ftr_cur_config` instead of `git pull` only. That fixed the problem.

**Comment by jeremylt** [comment]
Huh. My version of git doesn't seem to need the extra arguments for pull, but I'm glad it works for you.

**Comment by ArashMehraban** [comment]
I really should not be implementing on Noether, but I do my implementations in there using `vim`. I use the `git` version in Noether, but hey, it works :)

**Comment by valeriabarra** [comment]
@jeremylt, you probably have set what is your origin (you can verify this by running `git remote -v`.) 

@ArashMehraban you can add which remote you want to point to for pull/push, by running `git remote set-url origin <url>`

**Comment by valeriabarra** [comment]
The official git docs is currently down, but you can check this thread
https://stackoverflow.com/questions/42830557/git-remote-add-origin-vs-remote-set-url-origin
