### ISSUE TITLE
Julia style failing

### ISSUE THREAD

**Issue by LeilaGhaffari** [CEED/libCEED#717]
Julia style is failing due to the latest Julia release.

**Comment by pazner** [comment]
I can look into it, but likely won't get to it until next week. In the mean time we can probably pin the Julia version to 1.5 to avoid the errors if needed.

**Comment by jedbrown** [comment]
This seems to be passing now (e.g., https://github.com/CEED/libCEED/runs/2205761877?check_suite_focus=true) so maybe it was some sort of race condition with the Julia 1.6 release. I see JuliaFormatter has [new releases](https://github.com/domluna/JuliaFormatter.jl/tags) though I see they have the same formatting quirks as #693. Any other required maintenance or can this be closed with no changes?

**Comment by jeremylt** [comment]
We're passing now, so I'm closing at this time. Feel free to reopen if I'm missing something that needs to happen
