### ISSUE TITLE
Style Proposal

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#729]
Edit: Updating with a ToDo list

ToDo:
- [x] Update C style (#735)
- [x] Update fluids example
- [x] Update PETSc example suite (#726)
- [x] Update documentation (#703)

---

As @valeriabarra has pointed out a few times, our mix of styles is a bit of a mess. I can do a pass to unify and write a style guide, but I'd like to have some buy-in on the format.

Here is what I propose

* Documentation (currently very inconsistent)
  - One sentence per line
* C99/C++ (currently very inconsistent)
  - Google style variable/function names (we use modified Google style in `.astyle`)  (https://google.github.io/styleguide/cppguide.html)
  - Function names: `PascalCase` (current)
  - Type names: `PascalCase` (current)
  - Constant names: `UPPER_SNAKE_CASE` (current, different than Google)
  - Variable names: `snake_case` (currently we use a mix)
  - Struct variables: `snake_case`  (currently we use a mix)
* Python (currently consistent, change suggested)
  - PEP 8
  - Function/method names: `snake_case` (current)
  - Variable names: `snake_case` (current)
  - Whitespace: tab (proposed change, better accessibility)
* Rust (currently consistent)
  - Default Rust style (https://rust-lang.github.io/api-guidelines/naming.html)
  - Function/method names: `snake_case` (current)
  - Variable names: `snake_case` (current)
* Julia (currently consistent)
  - Default Julia style (https://docs.julialang.org/en/v1/manual/style-guide/)
  - Function/method/variable names: `nocase` or `snake_case` (current)
* Fortran (currently consistent)
  - defer modification until F77 support decision

I'm sure there are other things that can/should be added. This was just my first pass.

**Comment by valeriabarra** [comment]
Thanks Jeremy for opening the issue and the dicsussion.
I personally prefer anything but `nocase` and the current Fortran style (LOL), for acccessibility.

**Comment by jedbrown** [comment]
Underscores in Fortran are fraught. Some compilers mangle `foo` to `foo_` but `foo_bar` to `foo_bar__`, for example. The simplest convention is to avoid underscores in Fortran names, which are case-insensitive. Alternatively, we could use ISO C bindings, which fixes all of this and would allow an idiomatic modern Fortran interface.

I don't follow the desire to switch Python indentation to tabs. An advantage of spaces is you can always copy/paste and display using any tool while preserving indentation width. I'm also not wild about different conventions in different languages.

`snake_case` names are good with me for local variables and struct members, and consistent with style conventions of the other languages.

**Comment by jeremylt** [comment]
I'd be happy with `snake_case` everywhere except functions/methods (which are already constant for their language standards). That would be easy to whip up and would make things pretty consistent between the different languages, which would be nice.

I was thinking we would hold off on Fortran until we decide if/when to abandon F77 support. The interface is unused except for our test suite.

I'm not strongly arguing for tabs, but tabs are a nice accessibility feature for people with poorer eyesight who want to set deeper indentation to increase visual distinction. (though, its also possible to set your IDE to swap to tabs, adjust the tab size, then swap back to spaces when saving) PEP8 says that spaces are superior, and I'm fine with following PEP8 even if I disagree with it.
