### ISSUE TITLE
GNU extention warning

### ISSUE THREAD

**Issue by v-dobrev** [CEED/libCEED#742]
The following macros seem to use a GNU extension where the middle operand in `?:` is omitted:

https://github.com/CEED/libCEED/blob/caa531a793f3d84584e9b27c52e9992c3cc5ab43/include/ceed/ceed.h#L168-L176

I see warnings about this in MFEM when building with Apple clang with `-pedantic -std=c++11`. It will be nice if this use of a GNU extension can be avoided.

**Comment by jeremylt** [comment]
Strange, we put this in because of Clang. Can you provide the error message?

**Comment by v-dobrev** [comment]
One example of the warning I get is:
```console
fem/ceed/algebraic.cpp:493:14: warning: use of GNU ?: conditional expression extension, omitting middle operand
      [-Wgnu-conditional-omitted-operand]
      return CeedError(ceed, 1, "Vector sizes don't match");
             ^
./../libCEED/include/ceed/ceed.h:172:79: note: expanded from macro 'CeedError'
  (CeedErrorImpl((ceed), __FILE__, __LINE__, __func__, (ecode), __VA_ARGS__) ?: (ecode))
                                                                              ^
```
and the command line for this file is:
```console
mpicxx  -pedantic -O2 -g -std=c++11 -I./../hypre/src/hypre/include  -I./../libCEED/include -g  -c fem/ceed/algebraic.cpp -o fem/ceed/algebraic.o
```
The same warning is repeated multiple times for different locations and source files in `fem/ceed`.

**Comment by v-dobrev** [comment]
Thanks for addressing this issue @jeremylt!
