### ISSUE TITLE
Configuring LibCEED.jl instructions

### ISSUE THREAD

**Issue by valeriabarra** [CEED/libCEED#759]
Not sure if the reference to the "Configuring LibCEED.jl" section [here](https://github.com/CEED/libCEED/tree/main/julia/LibCEED.jl) is supposed to link to the following section in the same file, but if I click on it I see a 404.

**Comment by pazner** [comment]
Thanks for pointing this out. Yes, it's supposed to cross-reference the section in the same page. It should be fixed in #761.
