### ISSUE TITLE
CUDA bug for BP1 degree 5 q_extra 1

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#802]
Test passes (`CONVERGED_RTOL`) when using `/gpu/cuda/shared`, but not with `/gpu/cuda/ref` (`DIVERGED_ITS`).

It works for `-degree` 4, 6, and 7, and it works with `-q_extra` 0 and 2. This is using CUDA-11.4.

<details>

### Working
```console
$ build/petsc-bpsraw -ceed /gpu/cuda/shared -problem bp1 -degree 5 -q_extra 1 -ksp_max_it_clip 15,15

-- CEED Benchmark Problem 1 -- libCEED + PETSc --
  PETSc:
    PETSc Vec Type                     : seqcuda
  libCEED:
    libCEED Backend                    : /gpu/cuda/shared
    libCEED Backend MemType            : device
  Mesh:
    Number of 1D Basis Nodes (P)       : 6
    Number of 1D Quadrature Points (Q) : 7
    Global nodes                       : 1331
    Process Decomposition              : 1 1 1
    Local Elements                     : 8 = 2 2 2
    Owned nodes                        : 1331 = 11 11 11
    DoF per node                       : 1
  KSP:
    KSP Type                           : cg
    KSP Convergence                    : CONVERGED_RTOL
    Total KSP Iterations               : 9
    Final rnorm                        : 8.185631e-11
  Performance:
    Pointwise Error (max)              : 6.064044e-04
    CG Solve Time                      : 0.00187707 (0.00187707) sec
    DoFs/Sec in CG                     : 6.38176 (6.38176) million
```

### Broken
```console
$ build/petsc-bpsraw -ceed /gpu/cuda/ref -problem bp1 -degree 5 -q_extra 1 -ksp_max_it_clip 15,15

-- CEED Benchmark Problem 1 -- libCEED + PETSc --
  PETSc:
    PETSc Vec Type                     : seqcuda
  libCEED:
    libCEED Backend                    : /gpu/cuda/ref
    libCEED Backend MemType            : device
  Mesh:
    Number of 1D Basis Nodes (P)       : 6
    Number of 1D Quadrature Points (Q) : 7
    Global nodes                       : 1331
    Process Decomposition              : 1 1 1
    Local Elements                     : 8 = 2 2 2
    Owned nodes                        : 1331 = 11 11 11
    DoF per node                       : 1
  KSP:
    KSP Type                           : cg
    KSP Convergence                    : DIVERGED_ITS
    Total KSP Iterations               : 15
    Final rnorm                        : 5.455900e-07
  Performance:
    Pointwise Error (max)              : 9.596524e-04
    CG Solve Time                      : 0.0033586 (0.0033586) sec
    DoFs/Sec in CG                     : 5.94444 (5.94444) million
```

The same issue can be observed when swapping `bpsraw` for `bps`.

</details>

**Comment by jeremylt** [comment]
Hmm, this is working ok with PETSc main + libCEED main for gcc-10 + CUDA 11.1
```
$ /opt/cuda-11.1/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
$ gcc-10 -v
Using built-in specs.
COLLECT_GCC=gcc-10
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc10/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-pkgversion='Arch Linux 10.2.0-3' --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,fortran,lto --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror --program-suffix=-10 --enable-version-specific-runtime-libs --disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Arch Linux 10.2.0-3) 
```

**Comment by jedbrown** [comment]
I installed cuda-11.1 and 11.2 on lv, made clean builds of PETSc with each variant, and now run, pinning to our RTX 2080 Super.
```console
$ export PETSC_DIR=$HOME/petsc PETSC_ARCH=mpich-cuda11.2-g PETSC_OPTIONS='-use_gpu_aware_mpi 0'
$ export CUDA_VISIBLE_DEVICES=GPU-c4529365-8229-f689-b43d-ccd7f1677079
$ make CUDA_DIR=/usr/local/cuda-11.2 build/petsc-bpsraw -B -j8
$ build/petsc-bpsraw -ceed /gpu/cuda/ref -problem bp1 -degree 5 -q_extra 1 -ksp_max_it_clip 15,15 -ksp_monitor
```
The initial KSP residual is different. I need to check whether the qdata is different, and then probably just use printf debugging to localize. It produces the same result with CPU PETSc vectors, same result with `-q_extra 0`, same with `-degree 4`, but this combo is still lighting up with 11.2 and later.

**Comment by jedbrown** [comment]
@YohannDudouit @nbeams I've narrowed the issue down a bit, but it's still troubling. Adding this print statement makes the code behave correctly, though not all the lines are printed (only 6144 of 9261). Without that print statement, some of the weights are zero with cuda-11.2 and later (correct with cuda-11.1).
```diff
diff --git a/backends/cuda/ceed-cuda-basis.c b/backends/cuda/ceed-cuda-basis.c
index 646ce63e..e3ff6663 100644
--- a/backends/cuda/ceed-cuda-basis.c
+++ b/backends/cuda/ceed-cuda-basis.c
@@ -219,6 +219,7 @@ __device__ void weight3d(const CeedInt nelem, const CeedScalar *qweight1d,
           const int ind = e*BASIS_Q1D*BASIS_Q1D*BASIS_Q1D + i + j*BASIS_Q1D +
                           k*BASIS_Q1D*BASIS_Q1D; // sequential
           w[ind] = w1d[i]*w1d[j]*w1d[k];
+          printf("blockIdx %d blockDim %d threadIdx %d gridDim %d: %d %.9f\n", blockIdx.x, blockDim.x, threadIdx.x, gridDim.x, ind, w[ind]);
         }
 }
```

The grid layout here is rather poor and actually more code than in cuda/shared, so I wonder if we should just drop this approach and port the cuda/shared method back to cuda/ref. Of course if you have suggestions for debugging this weird issue, I'm all ears.

In the meantime, should we pin CI to cuda-11.1?

**Comment by jedbrown** [comment]
FWIW, compute-sanitizer reports clean with both 11.1 and 11.4, though the results are still different (correct in 11.1 and wrong in 11.4) when running under compute-sanitizer.

**Comment by jedbrown** [comment]
Well this is fun. I now have a laptop with a 3050 Ti and cuda-11.4.1 and the bug is not present. So to narrow down, it has only appeared on one machine with an RTX 2060 Super with cuda-11.2, 11.3, and 11.4. @jeremylt I assume you have cuda-11.4 now. Does it work or not on your machine?

**Comment by jeremylt** [comment]
I'm seeing the bug on a 2070 Super with 11.4.0

**Comment by jedbrown** [comment]
No, my mistake (fixed). It has 2080 Super (ours) and 1080 Ti (Qin's). The code executes correctly on the 1080 Ti (arch 61) and 3050 Ti (arch 86), but not the 2080 Super (arch 75).

To debug this sort of thing, we should probably allow the user to set gencode options via an environment variable.

**Comment by nbeams** [comment]
Just so I'm clear what's going on here, has someone kept a list of every known combination of hardware/CUDA version/driver version that is failing currently?  From reading the discussion, I think it's:

Fails: RTX 2080 -- CUDA 11.2, 11.3, 11.4 -- driver ? (assuming latest one since using CUDA 11.4)? 
OK: RTX 2080 -- CUDA 11.1 -- same driver as above

Was @jeremylt's test on the same machine as the ones @jedbrown did, or different machines?

And the problem only occurs in the  BP1, not any of the regular libCEED tests for the mass operator, correct?

**Comment by jeremylt** [comment]
My 2070 is ok with 11.1 as well, latest drivers

It looks like the 20XX cards we have fail with CUDA 11.3+ while 10XX and 30XX cards work fine with any CUDA.

**Comment by jedbrown** [comment]
I'm closing this since we worked around it in #803. This isn't very satisfying because who knows when the issue could strike us again.
