### ISSUE TITLE
Making QFunction Context Const

### ISSUE THREAD

**Issue by Steven-Roberts** [CEED/libCEED#86]
The context for a qfunction callback is documented as an in/out parameter. https://github.com/CEED/libCEED/blob/535acf402d3673fa5aa2d037f0e06810d1903c19/ceed-qfunction.c#L46-L47
For the cuda and occa backends, the goal is to have the qfunction being applied in parallel.  If the context is modified in a qfunction, however, this could lead to race conditions and other potential issues.  Is there any reason that the context cannot be declared constant?

**Comment by jeremylt** [comment]
On line 128 of the PETSc bp1.c example, there is a function that is writing to ctx.

**Comment by Steven-Roberts** [comment]
Ahh I had not noticed that.  I suppose the documentation will need to explain that atomics or other synchronization constructs are needed in a situation like this.

**Comment by jedbrown** [comment]
My theory was that if the context was to be used for monitoring, it would only be modified using atomics.  After merging active/passive, we could make a type of passive output that would be reduced with a user-specified operation such as sum or max.

**Comment by jeremylt** [comment]
Is there planned work here?

**Comment by jeremylt** [comment]
See Issue #183
