### ISSUE TITLE
Cannot compile libCEED-0.9.0

### ISSUE THREAD

**Issue by Vyrgyl** [CEED/libCEED#875]
Hi,

From a fresh release tarball, I do
make configure
make AVX=0

And I got the following errors.
Does anyone know what happens?

Thanks,
Virgil

[c.txt](https://github.com/CEED/libCEED/files/7894421/c.txt)

**Comment by jeremylt** [comment]
Unfortunately, the OCCA backend is experimental and not under active development. I recommend not compiling with the OCCA backend.

**Comment by Vyrgyl** [comment]
This is a real quick response, Jeremy, and I thank you for that.

**Comment by jeremylt** [comment]
Sure thing; happy to help.

FYI - If you're specifically interested in OCCA, we do have a branch to make that backend compile with the latest version of OCCA. The OCCA team never finished the work though and I don't know enough OCCA to finish it myself. Currently that backend only compiles with a specific commit off of OCCA main from some time in 2020.
