### ISSUE TITLE
Use of size_t where needed for COO assembly

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#884]
Although it's fairly reasonable for a single-node vector to have no more than 2B entries, it's much less reasonable for the number of entries in a COO matrix assembly to be less than 2B. And yet we place those in a `CeedVector` so we're currently limited to 2B entries, 
```c
CEED_EXTERN int CeedOperatorLinearAssemble(CeedOperator op, CeedVector values);
```
But when solving a scalar problem with Q_1 hexes, each element produces 64 values and thus we're limited to about 33M elements (33M dofs) per rank. I think we should upgrade to `size_t` for these sizes, even if our offsets in `CeedElemRestriction` stay 32-bit. (Increasing them to 64-bit has a nontrivial impact on memory bandwidth so we'll want to have a 32-bit path even if we enable 64-bit.)

**Comment by jeremylt** [comment]
I believe #913 addressed the vector size component of this. Do we want to close this until we have a need for 64 bit indices?

**Comment by jedbrown** [comment]
Yes, I think this has been addressed now.
