### ISSUE TITLE
t17-basis-f.f Failing

### ISSUE THREAD

**Issue by Steven-Roberts** [CEED/libCEED#89]
Although the Travis build seems to be fine, I am getting a segfault when I run t17-basis-f.f.  I believe the culprit is
https://github.com/CEED/libCEED/blob/a460c33b23cf49899be5782d753f25b389750a7f/tests/t17-basis-f.f#L89-L90
The 2 should be changed 1 to match the C version
https://github.com/CEED/libCEED/blob/a460c33b23cf49899be5782d753f25b389750a7f/tests/t17-basis.c#L40

**Comment by jeremylt** [comment]
Agreed, this was a typo on my part.

**Comment by jeremylt** [comment]
Fix incorporated into PR #41, but it revealed some sort of strange issue in interfacing between C and Fortran when dealing with the 3D case.

**Comment by jeremylt** [comment]
Closed by PR #41
