### ISSUE TITLE
GPU QF Assembly 

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#926]
We can half the memory required to assemble QFs on the GPU if we relax the ordering requirements for the assembled output vector for CeedOperatorLinearQFunctionAssemble

**Comment by jeremylt** [comment]
I think we can do this by using `CeedElemRestrictionGetStrides()`

**Comment by nbeams** [comment]
I'm not sure I understand what you mean -- what would the new output ordering be?

**Comment by jeremylt** [comment]
Whatever the backend uses in `CeedOperatorLinearQFunctionAssemble()` before copying into the l-vector

**Comment by nbeams** [comment]
How does that change the memory usage?

**Comment by jeremylt** [comment]
Currently we use `num_elem * num_qpts * problem_size_at_qpts * 2` scalars on the GPU for QF assembly, with the 2x factor coming from the fact that we replicate the lvector contents in an internally cached qvector layout. This would reduce to `num_elem * num_qpts * problem_size_at_qpts * 2` scalars. We've made a similar improvement on the CPU side for the OPT backends, but we can't replicate the trick we use there because we only assembly 8 elements at a time for the CPU opt backends

**Comment by nbeams** [comment]
Does this happen somewhere other than `CeedOperatorLinearAssembleQFunctionCore_Cuda` (or Hip)?   I don't see the extra memory usage from looking through it just now, though I see it creates a strided element restriction with particular strides, but does the restriction get used elsewhere?  (I just want to make sure I know the exact part of the code you're talking about.)

**Comment by jeremylt** [comment]
I'm super confused now. I put a `CeedElemRestrictionApply` into `CeedOperatorLinearAssembleQFunctionCore_Cuda` but I can't find it.

**Comment by jeremylt** [comment]
Ok, I can't find it, or any commit where it ever existed. I must be going slightly crazier
