### ISSUE TITLE
Operator Assembly Fails with mismatched input & output

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#987]
Given an operator, the `CeedOperatorLinearAssemble[Diagonal]` operation works only if the each input for the operator's QFunction has a matching output with the same `CeedEvalMode`. This was first discovered in the fluids example here, but is mostly easily/simply demonstrated via a Ratel test. Specifically, [t103](https://gitlab.com/micromorph/ratel/-/blob/main/tests/t103-static-elasticity.c) while applying the following patch:
<details>
<summary>Patch</summary>

```patch
diff --git i/src/ratel-fem.c w/src/ratel-fem.c
index 61efffc..efe644d 100644
--- i/src/ratel-fem.c
+++ w/src/ratel-fem.c
@@ -541,6 +541,10 @@ PetscErrorCode RatelSetupResidualJacobian_FEM(Ratel ratel, RatelMaterialData mat
     RatelDebug(ratel, "---- Setting up Jacobian evaluator");
     CeedQFunction qf_jacobian;
     CeedOperator  op_jacobian;
+    PetscBool testin      = PETSC_FALSE,
+              testingrad  = PETSC_FALSE,
+              testout     = PETSC_FALSE,
+              testoutgrad = PETSC_FALSE;
 
     // -- QFunction
     RatelCeedCall(ratel, CeedQFunctionCreateInterior(ceed, 1, material_data->jacobian, material_data->jacobian_loc, &qf_jacobian));
@@ -554,7 +558,11 @@ PetscErrorCode RatelSetupResidualJacobian_FEM(Ratel ratel, RatelMaterialData mat
       RatelCeedCall(ratel, CeedQFunctionAddInput(qf_jacobian, material_data->field_names[i], material_data->field_sizes[i], CEED_EVAL_NONE));
       // *INDENT-ON*
     }
+    if(testin) RatelCeedCall(ratel, CeedQFunctionAddInput(qf_jacobian, "testin", num_comp_u, CEED_EVAL_INTERP));
+    if(testingrad) RatelCeedCall(ratel, CeedQFunctionAddInput(qf_jacobian, "testingrad", num_comp_u*dim, CEED_EVAL_GRAD));
     RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "delta dv", num_comp_u * dim, CEED_EVAL_GRAD));
+    if(testout) RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "testout", num_comp_u, CEED_EVAL_INTERP));
+    if(testoutgrad) RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "testoutgrad", num_comp_u*dim, CEED_EVAL_GRAD));
     if (ratel->method == RATEL_METHOD_DYNAMIC_ELASTICITY) {
       RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "delta v", num_comp_u, CEED_EVAL_INTERP));
     }
@@ -572,6 +580,10 @@ PetscErrorCode RatelSetupResidualJacobian_FEM(Ratel ratel, RatelMaterialData mat
                                                 stored_fields[i]));
       // *INDENT-ON*
     }
+    if(testin) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testin", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
+    if(testout) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testout", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
+    if(testingrad) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testingrad", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
+    if(testoutgrad) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testoutgrad", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
     if (ratel->method == RATEL_METHOD_DYNAMIC_ELASTICITY) {
       RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "delta u", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
       RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "delta v", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));

```
</details>

The above will pass t103, but any combination of the booleans where `testin*` does not match `testout*` will fail the test.

This behavior has been verified for `/gpu/hip/ref` and `/cpu/self`. 

Side questions:
- Is it `CeedOperatorLinearAssemble` and `CeedOperatorLinearAssembleDiagonal`, or just one of them?

**Comment by jeremylt** [comment]
We know it's LinearAssemble. I suspect it is not LinearAssembleDiagonal. I'm not sure, but I think the assembly assumes B^TDB has the same B and B^T matrix.

**Comment by jeremylt** [comment]
@nbeams you looked at this code recently. Does my guess match with your knowledge?

**Comment by nbeams** [comment]
Is this the full patch?  If you are changing the number of inputs/outputs, wouldn't you want/need to change the QFunction itself in some cases as well?

**Comment by jrwrigh** [comment]
The patch just demonstrates the minimum required to duplicate the original issue; in the situation I ran into, I did want to use an extra input, but the resulting assembly was wrong. I then narrowed it down to just adding an input, which should have no effect, but was causing the assembly to be incorrect.

**Comment by jeremylt** [comment]
I'll create a new PR here in a moment, but reducing to a libCEED test is producing different results, interestingly.

**Comment by jedbrown** [comment]
> it's allowed to ignore some inputs/outputs that it doesn't need

You can ignore an input (i.e., outputs actually don't depend on it), but you can't ignore an output because the (perhaps uninitialized) memory will get used anyway. You can add an output and zero it.

**Comment by jrwrigh** [comment]
> >it's allowed to ignore some inputs/outputs that it doesn't need
>
> You can ignore an input (i.e., outputs actually don't depend on it), but you can't ignore an output because the (perhaps uninitialized) memory will get used anyway. You can add an output and zero it.

Yeah, I realized that after I sent that. Thought I edited the message, but evidently not.

**Comment by jeremylt** [comment]
I'm only able to reproduce this bug on main with CPU, not GPU.
