### ISSUE TITLE
Cannot set device ID through resource name

### ISSUE THREAD

**Issue by nbeams** [CEED/libCEED#999]
Setting GPU device ID when specifying a backend is broken.  Trying to add it gives an error, e.g.:

```
in CeedInit_Cuda(): Cuda backend cannot use resource: /gpu/cuda/ref:device_id=0
```

I think it stems from #863, specifically commit f87d896ccdb3ae7eb58212d71cf20ac055d48f9d ?

Was this unintended behavior?  Or do we want to add a different way of setting/configuring device ID?  

If removing this method of setting device ID was intentional, we should update the README (which currently explains how to set the device ID for CUDA/HIP/MAGMA backends).

**Comment by nbeams** [comment]
Fix how?  Was it not working correctly?  Or is it not supposed to work anymore (must specify whole backend)?

**Comment by jeremylt** [comment]
Wouldn't `strncmp(resource, "/gpu/cuda/gen", nrc)` return a truthy value for `/gpu/cuda` and reject resource?

**Comment by nbeams** [comment]
Yeah, I thought that was the goal originally, that just specifying `/gpu/cuda` would pick the "best" CUDA backend for you (which would be `cuda-gen`).

**Comment by nbeams** [comment]
At least, that was the goal in the PR that fixed the device ID setting previously: #740

**Comment by jeremylt** [comment]
Ahh, I'm seeing what's going on.

I think we need a blend of the two:
```
if (strncmp(resource, "/gpu/cuda", 9) && strncmp(resource, "/gpu/cuda/gen", 13))
```
The gen backend should only respond to these two matches.

**Comment by jeremylt** [comment]
I'd check against a copy of the string up to the :

**Comment by nbeams** [comment]
Just to be clear, are you planning to work on a fix for this, or should I?  I just don't want to duplicate work.

**Comment by jeremylt** [comment]
I can fix it in the morning

**Comment by YohannDudouit** [comment]
Regarding the `/gpu/cuda` being always `/gpu/cuda/gen`, how hard would it be that it picks `/gpu/cuda/gen` when the `CeedOperator` does not contain non-tensor basis, and `/gpu/cuda/shared` when the `CeedOperator` does contain a non-tensor basis?
Ideally, on mixed meshes, when using `/gpu/cuda` it would pick `/gpu/cuda/gen` on the tensor elements and `/gpu/cuda/shared` on the non-tensor elements. This would also help with the integration of libCEED,  users would not have to *explicitly* request a backend when using "non-tensor" elements as libCEED would provide a "good" default backend.

**Comment by nbeams** [comment]
Well, for one thing, if the MAGMA backend is enabled, it is better overall for non-tensor operators 😉 
(And should be improving soon; Ahmad has been working on collecting more data to tune the GEMM calls for different GPUs, and a more flexible framework for using it)

**Comment by jeremylt** [comment]
We currently have no way of knowing at the time that the backend is initialized that the user will create non-tensor bases. I'm not sure what would be a clean way to have `/gpu/cuda` fallback to `/gpu/cuda/shared` for non-tensor and `/gpu/cuda/gen` not do so. I think we'd be better off finishing the `/gpu/*/gen` refactor.
